

test_that("Checking DBF is writting the output in the correct directory...", {

  #Create matrix
  m <- create_3_rnd_clust()
  
  #Create an output directory in the current folder
  dir.create(path = "tmp_output", showWarnings = F)
  #Run DBF
  res <- find_gene_clusters(data = m,
                            output_path = "tmp_output",
                            name = "test_",
                            distance_method = "pearson",
                            k = 50,
                            fdr = 10,
                            silent = FALSE,
                            inflation = 2,
                            seed = 123)
  #Test results
  out <- file.exists("tmp_output/test_.dbf_out.txt")
  expect_equal(out, TRUE)
  #Remove temporary files
  file.remove("tmp_output/test_.dbf_out.txt")
  file.remove("tmp_output/test_.mcl_out.txt")
  file.remove("tmp_output")
})




test_that("Checking output matrix generated by find_gene_clusters...", {
  #Create matrix containing 3 signatures
  set.seed(123)
  m <- create_3_rnd_clust()
  res <- find_gene_clusters(data=m,
                            name = "test",
                            distance_method="pearson",
                            inflation = 2,
                            k=50,
                            fdr = 10,
                            seed = 123)
  
  #=======================================================
  # Test name of temporary files
  expect_equal(res@name, "test")
  expect_true(file.exists("test.dbf_out.txt"))
  expect_true(file.exists("test.mcl_out.txt"))
  expect_equal(length(res@name), 1)
  expect_that(res@name, is_a("character"))
  
  
  #=======================================================
  # Test matrix in res@data
  expect_equal(round(sum(res@data), 3), 5086.909)
  expect_equal(round(mean(res@data), 7), 0.6837243)
  expect_equal(round(median(res@data), 7), 0.3038707)
  expect_equal(round(sd(res@data), 6), 2.107101)
  
  expect_equal(round(sum(quantile(res@data)["0%"]), 6), -5.274385)
  expect_equal(round(sum(quantile(res@data)["25%"]), 6), -0.754237)
  expect_equal(round(sum(quantile(res@data)["50%"]), 6), 0.303871)
  expect_equal(round(sum(quantile(res@data)["75%"]), 6), 2.134471)
  expect_equal(round(sum(quantile(res@data)["100%"]), 6), 6.971585)
  
  expect_equal(round(sum(colMeans(res@data)),5), 13.67449)
  expect_equal(round(sum(rowMeans(res@data)),4), 254.3454)
  
  expect_equal(round(max(res@data),6), 6.971585)
  
  expect_equal(ncol(res@data), 20)
  expect_equal(colnames(res@data), paste0("sample", seq(1,20)))
  
  expect_equal(nrow(res@data), 372)
  
  expect_equal(nrow(res@data), length(get_genes(res)))
  expect_equal(rownames(res@data), get_genes(res))
  expect_equal(rownames(res@data), names(res@gene_clusters))
  expect_equal(nrow(res@data), length(get_genes(res)))
  expect_equal(nrow(res@data), length(res@gene_clusters))
  
  expect_equal(round(sum(res@data^2), 2), 36506.27)
  
  expect_that(res@data, is_a("matrix"))
  
  expect_equal(length(res@data), 7440)
  
  
  #=======================================================
  # Test observed distances in res@distances
  expect_equal(round(sum(res@distances), 3), 1942.611)
  expect_equal(round(mean(res@distances), 7), 0.4856527)
  expect_equal(round(median(res@distances), 7), 0.502099)
  expect_equal(round(sd(res@distances), 6), 0.063969)
  
  expect_equal(round(sum(quantile(res@distances)["0%"]), 6), 0.133025)
  expect_equal(round(sum(quantile(res@distances)["25%"]), 6), 0.491859)
  expect_equal(round(sum(quantile(res@distances)["50%"]), 6), 0.502099)
  expect_equal(round(sum(quantile(res@distances)["75%"]), 6), 0.510083)
  expect_equal(round(sum(quantile(res@distances)["100%"]), 6), 0.536909)
  
  expect_equal(length(res@distances), 4000)
  
  expect_equal(round(sum(res@distances^2), 2), 959.8)
  
  expect_that(res@distances, is_a("numeric"))
  
  
  #=======================================================
  # Test simulated distances in res@simulated_distances
  expect_equal(round(sum(res@simulated_distances), 3), 1964.139)
  expect_equal(round(mean(res@simulated_distances), 7), 0.4910349)
  expect_equal(round(median(res@simulated_distances), 7), 0.4912826)
  expect_equal(round(sd(res@simulated_distances), 6), 0.0117)
  
  expect_equal(round(sum(quantile(res@simulated_distances)["0%"]), 6), 0.448651)
  expect_equal(round(sum(quantile(res@simulated_distances)["25%"]), 6), 0.483333)
  expect_equal(round(sum(quantile(res@simulated_distances)["50%"]), 6), 0.491283)
  expect_equal(round(sum(quantile(res@simulated_distances)["75%"]), 6), 0.498785)
  expect_equal(round(sum(quantile(res@simulated_distances)["100%"]), 6), 0.538793)
  
  expect_equal(length(res@simulated_distances), 4000)
  
  expect_equal(round(sum(res@simulated_distances^2), 2), 965.01)
  
  expect_that(res@simulated_distances, is_a("numeric"))
  
  
  #=======================================================
  # Test critical distance in res@critical_distance
  expect_equal(round(res@critical_distance, 7), 0.4628177)
  expect_that(res@critical_distance, is_a("numeric"))
  expect_equal(length(res@critical_distance), 1)
  
  
  #=======================================================
  # Test gene clusters in res@gene_clusters
  expect_equal(round(sum(res@gene_clusters), 3), 714)
  expect_equal(round(mean(res@gene_clusters), 6), 1.919355)
  expect_equal(median(res@gene_clusters), 2)
  expect_equal(round(sd(res@gene_clusters), 6), 0.796862)
  expect_equal(min(res@gene_clusters), 1)
  expect_equal(max(res@gene_clusters), 3)
  
  expect_equal(unique(res@gene_clusters), c(1,2,3))
  expect_equal(length(res@gene_clusters), 372)
  expect_equal(length(res@gene_clusters[res@gene_clusters == 1]), 134)
  expect_equal(length(res@gene_clusters[res@gene_clusters == 2]), 134)
  expect_equal(length(res@gene_clusters[res@gene_clusters == 3]), 104)
  
  expect_equal(names(res@gene_clusters), get_genes(res))
  expect_equal(names(res@gene_clusters[res@gene_clusters == 1]), get_genes(res, cluster = 1))
  expect_equal(names(res@gene_clusters[res@gene_clusters == 2]), get_genes(res, cluster = 2))
  expect_equal(names(res@gene_clusters[res@gene_clusters == 3]), get_genes(res, cluster = 3))
  expect_equal(names(res@gene_clusters), rownames(res@data))
  
  expect_that(res@gene_clusters, is_a("numeric"))
  
  
  #=======================================================
  # Test size of gene clusters in res@size
  expect_equal(res@size, c(134, 134, 104))
  expect_that(res@size, is_a("integer"))
  expect_equal(max(res@size), 134)
  expect_equal(min(res@size), 104)
  expect_equal(length(res@size), 3)
  
  expect_equal(res@size[1], length(res@gene_clusters[res@gene_clusters == 1]))
  expect_equal(res@size[2], length(res@gene_clusters[res@gene_clusters == 2]))
  expect_equal(res@size[3], length(res@gene_clusters[res@gene_clusters == 3]))
  expect_equal(res@size[1], length(get_genes(res, cluster = 1)))
  expect_equal(res@size[2], length(get_genes(res, cluster = 2)))
  expect_equal(res@size[3], length(get_genes(res, cluster = 3)))
  
  
  #=======================================================
  # Test parameters in res@parameters
  expect_that(res@parameters, is_a("list"))
  expect_equal(length(res@parameters), 7)
  expect_equal(names(res@parameters), c("distance_method",
                                        "k",
                                        "fdr",
                                        "seed",
                                        "inflation",
                                        "min_cluster_size",
                                        "av_dot_prod_min"))
  
  expect_equal(res@parameters$distance_method, "pearson")
  expect_that(res@parameters$distance_method, is_a("character"))
  expect_equal(length(res@parameters$distance_method), 1)
  
  expect_equal(res@parameters$k, 50)
  expect_that(res@parameters$k, is_a("numeric"))
  expect_equal(length(res@parameters$k), 1)
  
  expect_equal(res@parameters$fdr, 10)
  expect_that(res@parameters$fdr, is_a("numeric"))
  expect_equal(length(res@parameters$fdr), 1)
  
  expect_equal(res@parameters$seed, 123)
  expect_that(res@parameters$seed, is_a("numeric"))
  expect_equal(length(res@parameters$seed), 1)
  
  expect_equal(res@parameters$inflation, 2)
  expect_that(res@parameters$inflation, is_a("numeric"))
  expect_equal(length(res@parameters$inflation), 1)
  
  expect_equal(res@parameters$min_cluster_size, 10)
  expect_that(res@parameters$min_cluster_size, is_a("numeric"))
  expect_equal(length(res@parameters$min_cluster_size), 1)
  
  expect_equal(res@parameters$av_dot_prod_min, 0)
  expect_that(res@parameters$av_dot_prod_min, is_a("numeric"))
  expect_equal(length(res@parameters$av_dot_prod_min), 1)
  
  
  #Remove output files
  file.remove("test.dbf_out.txt")
  file.remove("test.mcl_out.txt")
})



