test_that("Checking DBF is writting the output in the correct directory...", {
  
  set_verbosity(0)
  
  #Create matrix
  m <- create_3_rnd_clust()
  
  #Create an output directory in the current folder
  dir.create(path = "tmp_output", showWarnings = F)
  #Run DBF
  res <- DBF(data = m,
             output_path = "tmp_output",
             name = "test_",
             distance_method = "pearson",
             k = 50,
             fdr = 10,
             seed = 123)
  #Test results
  out <- file.exists("tmp_output/test_.dbf_out.txt")
  expect_equal(out, TRUE)
  #Remove temporary files
  file.remove("tmp_output/test_.dbf_out.txt")
  unlink("tmp_output", recursive = T)
})




test_that("Checking output matrix generated by find_gene_clusters...", {
  
  set_verbosity(0)
  
  #Create matrix containing 3 signatures
  m <- create_4_rnd_clust()
  
  ## A rather stringent version
  res <- DBF(data=m,
             distance_method="pearson",
             k=75,
             row_sum=-Inf,
             highest=0.3,
             fdr = 1e-8,
             name = "test",
             output_path = ".")
  
  #=======================================================
  # Test name of temporary files
  expect_equal(res@parameters$name, "test")
  expect_true(file.exists("test.dbf_out.txt"))
  expect_equal(length(res@parameters$name), 1)
  expect_that(res@parameters$name, is_a("character"))
  
  
  #=======================================================
  # Test matrix in res@data
  expect_equal(round(sum(res@data), 3), 2188.346) 
  expect_equal(round(mean(res@data), 6), 0.296524)
  expect_equal(round(median(res@data), 6), 0.083721)
  expect_equal(round(sd(res@data), 6), 2.123212)
  
  expect_equal(round(sum(quantile(res@data)["0%"]), 6), -5.806817)
  expect_equal(round(sum(quantile(res@data)["25%"]), 6), -1.013447)
  expect_equal(round(sum(quantile(res@data)["50%"]), 6), 0.083721)
  expect_equal(round(sum(quantile(res@data)["75%"]), 6), 1.34164)
  expect_equal(round(sum(quantile(res@data)["100%"]), 6), 7.073935)
  
  expect_equal(round(sum(colMeans(res@data)),5), 5.93048)
  expect_equal(round(sum(rowMeans(res@data)),4), 109.4173)
  
  expect_equal(round(max(res@data),6), 7.073935)
  
  expect_equal(ncol(res@data), 20)
  expect_equal(colnames(res@data), paste0("sample", seq(1,20)))
  
  expect_equal(nrow(res@data), 369)
  
  expect_equal(nrow(res@data), length(get_genes(res)))
  expect_equal(rownames(res@data), get_genes(res))
  expect_equal(rownames(res@data), unlist(res@gene_clusters, use.names = F))
  expect_equal(nrow(res@data), length(get_genes(res)))
  expect_equal(nrow(res@data), length(unlist(res@gene_clusters, use.names = F)))
  
  expect_equal(round(sum(res@data^2), 2), 33913.65)
  
  expect_that(res@data, is_a("matrix"))
  
  expect_equal(length(res@data), 7380)
  
  
  #=======================================================
  # Test observed distances in res@dbf_output$dknn
  expect_equal(round(sum(res@dbf_output$dknn), 3), 2070.863)
  expect_equal(round(mean(res@dbf_output$dknn), 7), 0.5177157)
  expect_equal(round(median(res@dbf_output$dknn), 7), 0.5333734)
  expect_equal(round(sd(res@dbf_output$dknn), 6), 0.058557)
  
  expect_equal(round(sum(quantile(res@dbf_output$dknn)["0%"]), 6), 0.151747)
  expect_equal(round(sum(quantile(res@dbf_output$dknn)["25%"]), 6), 0.52163)
  expect_equal(round(sum(quantile(res@dbf_output$dknn)["50%"]), 6), 0.533373)
  expect_equal(round(sum(quantile(res@dbf_output$dknn)["75%"]), 6), 0.541248)
  expect_equal(round(sum(quantile(res@dbf_output$dknn)["100%"]), 6), 0.569402)
  
  expect_equal(length(res@dbf_output$dknn), 4000)
  
  expect_equal(round(sum(res@dbf_output$dknn^2), 2), 1085.83)
  
  expect_that(res@dbf_output$dknn, is_a("numeric"))
  
  
  #=======================================================
  # Test simulated distances in res@dbf_output$simulated_dknn
  expect_equal(round(sum(res@dbf_output$simulated_dknn), 3), 2153.312)
  expect_equal(round(mean(res@dbf_output$simulated_dknn), 7), 0.538328)
  expect_equal(round(median(res@dbf_output$simulated_dknn), 7), 0.538304)
  expect_equal(round(sd(res@dbf_output$simulated_dknn), 6), 0.009098)
  
  expect_equal(round(sum(quantile(res@dbf_output$simulated_dknn)["0%"]), 6), 0.504041)
  expect_equal(round(sum(quantile(res@dbf_output$simulated_dknn)["25%"]), 6), 0.532663)
  expect_equal(round(sum(quantile(res@dbf_output$simulated_dknn)["50%"]), 6), 0.538304)
  expect_equal(round(sum(quantile(res@dbf_output$simulated_dknn)["75%"]), 6), 0.544447)
  expect_equal(round(sum(quantile(res@dbf_output$simulated_dknn)["100%"]), 6), 0.572353)
  
  expect_equal(length(res@dbf_output$simulated_dknn), 4000)
  
  expect_equal(round(sum(res@dbf_output$simulated_dknn^2), 2), 1159.52)
  
  expect_that(res@dbf_output$simulated_dknn, is_a("numeric"))
  
  
  #=======================================================
  # Test critical distance in res@critical_distance
  expect_equal(round(res@dbf_output$critical_distance, 7), 0.4772475)
  expect_that(res@dbf_output$critical_distance, is_a("numeric"))
  expect_equal(length(res@dbf_output$critical_distance), 1)
  
  
  #=======================================================
  # Test gene clusters in res@gene_clusters
  expect_equal(names(res@gene_clusters), "1")
  expect_equal(length(res@gene_clusters$`1`), 369)
  
  expect_equal(res@gene_clusters$`1`, get_genes(res))
  expect_equal(res@gene_clusters$`1`, get_genes(res, cluster = 1))
  expect_equal(res@gene_clusters$`1`, rownames(res@data))
  
  expect_that(res@gene_clusters, is_a("list"))
  expect_that(res@gene_clusters$`1`, is_a("character"))
  
  
  #=======================================================
  # Test size of gene clusters in res@gene_clusters_metadata$size
  expect_equal(res@gene_clusters_metadata$size, 369)
  expect_that(res@gene_clusters_metadata$size, is_a("integer"))
  expect_equal(length(res@gene_clusters_metadata$size), 1)
  
  expect_equal(res@gene_clusters_metadata$size[1],
               length(res@gene_clusters$`1`))
  expect_equal(res@gene_clusters_metadata$size[1],
               length(get_genes(res, cluster = 1)))
  
  
  #=======================================================
  # Test parameters in res@parameters
  expect_that(res@parameters, is_a("list"))
  expect_equal(length(res@parameters), 8)
  expect_equal(names(res@parameters), c("algorithm",
                                        "name",
                                        "distance_method",
                                        "k",
                                        "highest",
                                        "fdr",
                                        "row_sum",
                                        "seed"))
  
  expect_equal(res@parameters$algorithm, "DBFMCL")
  expect_that(res@parameters$algorithm, is_a("character"))
  expect_equal(length(res@parameters$algorithm), 1)
  
  expect_equal(res@parameters$distance_method, "pearson")
  expect_that(res@parameters$distance_method, is_a("character"))
  expect_equal(length(res@parameters$distance_method), 1)
  
  expect_equal(res@parameters$k, 75)
  expect_that(res@parameters$k, is_a("numeric"))
  expect_equal(length(res@parameters$k), 1)
  
  expect_equal(res@parameters$highest, 0.3)
  expect_that(res@parameters$highest, is_a("numeric"))
  expect_equal(length(res@parameters$highest), 1)
  
  expect_equal(res@parameters$fdr, 1e-08)
  expect_that(res@parameters$fdr, is_a("numeric"))
  expect_equal(length(res@parameters$fdr), 1)
  
  expect_equal(res@parameters$row_sum, -Inf)
  expect_that(res@parameters$row_sum, is_a("numeric"))
  expect_equal(length(res@parameters$row_sum), 1)
  
  expect_equal(res@parameters$seed, 123)
  expect_that(res@parameters$seed, is_a("numeric"))
  expect_equal(length(res@parameters$seed), 1)
  
  
  #Remove output files
  file.remove("test.dbf_out.txt")
})

test_that("Checking DBF is working with Sparse Matrices...", {
  
  set_verbosity(0)
  
  # Create a sparseMatrix
  m <- as(create_3_rnd_clust(), "sparseMatrix")
  expect_equal(inherits(m, "dgCMatrix"), TRUE)
  expect_equal(ncol(m), 20)
  expect_equal(nrow(m), 4000)
  
  #Run DBF with a Sparse Matrix
  res_1 <- DBF(data = m,
             name = "test_",
             distance_method = "pearson",
             k = 50,
             fdr = 10,
             seed = 123)
  
  # Create a normal matrix 
  m <- create_3_rnd_clust()
  expect_equal(ncol(m), 20)
  expect_equal(nrow(m), 4000)  
  
  #Run DBF with a Sparse Matrix
  res_2 <- DBF(data = m,
               name = "test_",
               distance_method = "pearson",
               k = 50,
               fdr = 10,
               seed = 123)
  expect_true(all(unlist(res_1@gene_clusters) == unlist(res_2@gene_clusters)))
  
})



# ==============================================================================
# Test data argument
# ==============================================================================

test_that("Checking stop if data argument is NULL", {
  # Set verbosity to 0
  set_verbosity(0)
  
  #Create matrix containing 3 signatures
  m <- create_4_rnd_clust()
  
  expect_error(DBF(data=NULL,
                   distance_method="pearson",
                   k=75,
                   row_sum=-Inf,
                   highest=0.3,
                   fdr = 1e-8,
                   name = "test"))
})


# ==============================================================================
# Test highest arguement
# ==============================================================================

test_that("Checking stop if highest argument > 1 or <0", {
  # Set verbosity to 0
  set_verbosity(0)
  
  #Create matrix containing 3 signatures
  m <- create_4_rnd_clust()
  
  expect_error(DBF(data=m,
                   distance_method="pearson",
                   k=75,
                   row_sum=-Inf,
                   highest=-0.1,
                   fdr = 1e-8,
                   name = "test"))
  
  expect_error(DBF(data=m,
                   distance_method="pearson",
                   k=75,
                   row_sum=-Inf,
                   highest=101,
                   fdr = 1e-8,
                   name = "test"))
})


test_that("Checking dbf() when highest argumenet is set to 0", {
  # Set verbosity to 0
  set_verbosity(0)
  
  #Create matrix containing 3 signatures
  m <- create_4_rnd_clust()
  
  res <- DBF(data=m,
             distance_method="pearson",
             k=75,
             row_sum=-Inf,
             highest=0,
             fdr = 1e-8,
             name = "test",
             output_path = ".")
  
  expect_equal(res@gene_clusters_metadata$cluster_id, 1)
  expect_equal(res@gene_clusters_metadata$number, "1")
  expect_equal(res@gene_clusters_metadata$size, 296)
  expect_equal(unlist(res@gene_clusters, use.names = F), c(
    "gene146", "gene189", "gene150", "gene117", "gene190", "gene135",
    "gene165", "gene186", "gene180", "gene155", "gene144", "gene132",
    "gene106", "gene192", "gene111", "gene153", "gene108", "gene159",
    "gene133", "gene166", "gene112", "gene143", "gene126", "gene145",
    "gene184", "gene122", "gene161", "gene176", "gene193", "gene137",
    "gene168", "gene160", "gene147", "gene107", "gene129", "gene188",
    "gene101", "gene104", "gene109", "gene114", "gene127", "gene157",
    "gene173", "gene197", "gene191", "gene177", "gene103", "gene105",
    "gene194", "gene163", "gene121", "gene116", "gene162", "gene158",
    "gene178", "gene175", "gene124", "gene141", "gene171", "gene128",
    "gene142", "gene198", "gene140", "gene119", "gene183", "gene167",
    "gene200", "gene199", "gene148", "gene174", "gene113", "gene151",
    "gene136", "gene179", "gene138", "gene181", "gene154", "gene130",
    "gene118", "gene115", "gene182", "gene134", "gene195", "gene164",
    "gene185", "gene120", "gene152", "gene149", "gene172", "gene131",
    "gene196", "gene110", "gene170", "gene125", "gene156", "gene123",
    "gene169", "gene102", "gene139", "gene187", "gene285", "gene273",
    "gene245", "gene272", "gene249", "gene230", "gene256", "gene225",
    "gene289", "gene286", "gene278", "gene282", "gene275", "gene214",
    "gene248", "gene277", "gene241", "gene206", "gene251", "gene298",
    "gene236", "gene267", "gene222", "gene290", "gene299", "gene223",
    "gene266", "gene217", "gene293", "gene229", "gene283", "gene300",
    "gene263", "gene235", "gene250", "gene212", "gene259", "gene219",
    "gene287", "gene233", "gene262", "gene239", "gene255", "gene258",
    "gene393", "gene203", "gene207", "gene240", "gene216", "gene232",
    "gene215", "gene253", "gene269", "gene237", "gene294", "gene390",
    "gene284", "gene247", "gene242", "gene312", "gene244", "gene297",
    "gene281", "gene226", "gene314", "gene1616", "gene76", "gene279",
    "gene316", "gene254", "gene246", "gene386", "gene364", "gene270",
    "gene369", "gene292", "gene318", "gene268", "gene288", "gene315",
    "gene398", "gene238", "gene387", "gene257", "gene363", "gene27",
    "gene37", "gene227", "gene220", "gene32", "gene234", "gene334",
    "gene838", "gene70", "gene202", "gene330", "gene55", "gene291",
    "gene208", "gene67", "gene320", "gene80", "gene3528", "gene382",
    "gene59", "gene326", "gene379", "gene16", "gene12", "gene84",
    "gene322", "gene205", "gene221", "gene329", "gene45", "gene295",
    "gene88", "gene271", "gene260", "gene224", "gene19", "gene201",
    "gene296", "gene324", "gene61", "gene211", "gene243", "gene349",
    "gene313", "gene306", "gene331", "gene280", "gene261", "gene368",
    "gene213", "gene209", "gene350", "gene78", "gene327", "gene3485",
    "gene73", "gene389", "gene319", "gene353", "gene36", "gene29",
    "gene397", "gene3991", "gene366", "gene39", "gene362", "gene1503",
    "gene7", "gene335", "gene2", "gene365", "gene57", "gene228",
    "gene86", "gene218", "gene9", "gene52", "gene210", "gene265",
    "gene51", "gene66", "gene340", "gene378", "gene64", "gene336",
    "gene358", "gene264", "gene1501", "gene13", "gene274", "gene252",
    "gene1267", "gene4", "gene1", "gene56", "gene394", "gene74",
    "gene34", "gene311", "gene2184", "gene79", "gene332", "gene93",
    "gene303", "gene2725", "gene341", "gene301", "gene385", "gene351",
    "gene1931", "gene42"
  ))
})

# ==============================================================================
# Test name arguement
# ==============================================================================

test_that("Checking if name is set to 'exprs' when name arguement is NULL", {
  # Set verbosity to 0
  set_verbosity(0)
  
  #Create matrix containing 3 signatures
  m <- create_4_rnd_clust()
  
  ## A rather stringent version
  res <- DBF(data=m,
             distance_method="pearson",
             k=75,
             row_sum=-Inf,
             highest=0.3,
             fdr = 1e-8,
             name = NULL)
  expect_equal(res@parameters$name, "exprs")
})


# ==============================================================================
# Test k argument
# ==============================================================================

test_that("Checking dbf() when k argument is set to 25", {
  # Set verbosity to 0
  set_verbosity(0)
  
  #Create matrix containing 3 signatures
  m <- create_4_rnd_clust()
  
  res <- DBF(data=m,
             distance_method="pearson",
             k=25,
             row_sum=-Inf,
             highest=0.3,
             fdr = 1e-8,
             name = "test",
             output_path = ".")
  
  expect_equal(res@gene_clusters_metadata$cluster_id, 1)
  expect_equal(res@gene_clusters_metadata$number, "1")
  expect_equal(res@gene_clusters_metadata$size, 327)
  expect_equal(unlist(res@gene_clusters, use.names = F), c(
    "gene192", "gene146", "gene190", "gene189", "gene155", "gene165",
    "gene150", "gene144", "gene153", "gene117", "gene135", "gene126",
    "gene180", "gene133", "gene186", "gene108", "gene106", "gene168",
    "gene159", "gene112", "gene132", "gene145", "gene111", "gene137",
    "gene143", "gene166", "gene184", "gene109", "gene176", "gene161",
    "gene122", "gene160", "gene105", "gene114", "gene101", "gene147",
    "gene188", "gene194", "gene191", "gene104", "gene127", "gene107",
    "gene124", "gene129", "gene171", "gene193", "gene197", "gene116",
    "gene158", "gene140", "gene121", "gene173", "gene200", "gene157",
    "gene128", "gene177", "gene162", "gene175", "gene198", "gene103",
    "gene119", "gene163", "gene142", "gene183", "gene141", "gene138",
    "gene167", "gene151", "gene136", "gene179", "gene113", "gene118",
    "gene199", "gene154", "gene178", "gene181", "gene174", "gene148",
    "gene115", "gene130", "gene134", "gene195", "gene164", "gene120",
    "gene152", "gene182", "gene185", "gene172", "gene149", "gene110",
    "gene102", "gene125", "gene131", "gene169", "gene123", "gene196",
    "gene170", "gene156", "gene272", "gene139", "gene286", "gene285",
    "gene222", "gene187", "gene245", "gene273", "gene256", "gene230",
    "gene223", "gene298", "gene249", "gene282", "gene214", "gene289",
    "gene266", "gene278", "gene225", "gene241", "gene236", "gene275",
    "gene248", "gene235", "gene290", "gene206", "gene277", "gene300",
    "gene251", "gene293", "gene259", "gene233", "gene267", "gene258",
    "gene229", "gene312", "gene283", "gene287", "gene232", "gene326",
    "gene316", "gene219", "gene297", "gene253", "gene255", "gene207",
    "gene217", "gene284", "gene212", "gene239", "gene299", "gene250",
    "gene393", "gene263", "gene281", "gene216", "gene237", "gene314",
    "gene215", "gene269", "gene244", "gene279", "gene70", "gene84",
    "gene55", "gene76", "gene29", "gene291", "gene242", "gene288",
    "gene80", "gene203", "gene315", "gene27", "gene363", "gene59",
    "gene262", "gene254", "gene32", "gene386", "gene247", "gene334",
    "gene379", "gene246", "gene12", "gene205", "gene37", "gene387",
    "gene390", "gene268", "gene329", "gene226", "gene270", "gene364",
    "gene397", "gene294", "gene280", "gene306", "gene261", "gene238",
    "gene398", "gene240", "gene39", "gene292", "gene2", "gene234",
    "gene88", "gene227", "gene350", "gene320", "gene220", "gene368",
    "gene1616", "gene13", "gene257", "gene19", "gene369", "gene209",
    "gene382", "gene366", "gene365", "gene213", "gene16", "gene7",
    "gene296", "gene330", "gene322", "gene221", "gene201", "gene318",
    "gene208", "gene335", "gene57", "gene67", "gene218", "gene260",
    "gene324", "gene210", "gene3991", "gene78", "gene340", "gene378",
    "gene349", "gene362", "gene1", "gene34", "gene61", "gene271",
    "gene74", "gene295", "gene211", "gene56", "gene45", "gene51",
    "gene73", "gene36", "gene838", "gene327", "gene224", "gene331",
    "gene319", "gene202", "gene274", "gene385", "gene9", "gene243",
    "gene31", "gene303", "gene228", "gene396", "gene311", "gene252",
    "gene79", "gene351", "gene82", "gene389", "gene332", "gene313",
    "gene64", "gene3528", "gene353", "gene71", "gene1267", "gene373",
    "gene83", "gene301", "gene86", "gene341", "gene339", "gene358",
    "gene264", "gene4", "gene94", "gene372", "gene11", "gene93",
    "gene355", "gene25", "gene342", "gene42", "gene10", "gene317",
    "gene371", "gene370", "gene89", "gene81", "gene2565", "gene367",
    "gene6", "gene336", "gene14", "gene231", "gene265", "gene58",
    "gene63", "gene323", "gene337", "gene22", "gene2157", "gene359",
    "gene52", "gene1501", "gene3485", "gene328", "gene17", "gene276",
    "gene3609", "gene394", "gene66"
  ))
})


# ==============================================================================
# Test row_sum argument
# ==============================================================================

test_that("Checking dbf() when row_sum argument is set to 5", {
  # Set verbosity to 0
  set_verbosity(0)
  
  #Create matrix containing 3 signatures
  m <- create_4_rnd_clust()
  
  res <- DBF(data=m,
             distance_method="pearson",
             k=75,
             row_sum=5,
             highest=0.3,
             fdr = 1e-8,
             name = "test",
             output_path = ".")
  
  expect_equal(res@gene_clusters_metadata$cluster_id, 1)
  expect_equal(res@gene_clusters_metadata$number, "1")
  expect_equal(res@gene_clusters_metadata$size, 214)
  expect_equal(unlist(res@gene_clusters, use.names = F), c(
    "gene146", "gene189", "gene150", "gene117", "gene190", "gene135",
    "gene165", "gene186", "gene180", "gene155", "gene144", "gene132",
    "gene106", "gene192", "gene111", "gene153", "gene108", "gene159",
    "gene133", "gene166", "gene112", "gene143", "gene126", "gene145",
    "gene184", "gene122", "gene161", "gene176", "gene193", "gene137",
    "gene168", "gene160", "gene147", "gene107", "gene129", "gene188",
    "gene101", "gene104", "gene109", "gene114", "gene127", "gene157",
    "gene173", "gene197", "gene191", "gene177", "gene103", "gene105",
    "gene194", "gene163", "gene121", "gene116", "gene162", "gene158",
    "gene178", "gene175", "gene124", "gene141", "gene171", "gene128",
    "gene142", "gene198", "gene140", "gene119", "gene183", "gene167",
    "gene199", "gene148", "gene174", "gene113", "gene200", "gene151",
    "gene136", "gene179", "gene138", "gene181", "gene154", "gene130",
    "gene118", "gene115", "gene182", "gene134", "gene195", "gene164",
    "gene185", "gene120", "gene152", "gene149", "gene172", "gene131",
    "gene196", "gene110", "gene170", "gene125", "gene156", "gene123",
    "gene102", "gene169", "gene139", "gene187", "gene76", "gene12",
    "gene55", "gene59", "gene16", "gene37", "gene32", "gene84",
    "gene27", "gene78", "gene80", "gene61", "gene88", "gene45",
    "gene36", "gene67", "gene7", "gene29", "gene1", "gene2",
    "gene39", "gene70", "gene57", "gene51", "gene19", "gene13",
    "gene86", "gene73", "gene9", "gene56", "gene64", "gene71",
    "gene94", "gene58", "gene34", "gene79", "gene1456", "gene74",
    "gene25", "gene31", "gene93", "gene3779", "gene66", "gene11",
    "gene6", "gene83", "gene4", "gene42", "gene52", "gene10",
    "gene35", "gene96", "gene87", "gene82", "gene3924", "gene69",
    "gene90", "gene63", "gene28", "gene17", "gene46", "gene14",
    "gene98", "gene1154", "gene1360", "gene20", "gene85", "gene22",
    "gene95", "gene1721", "gene44", "gene3", "gene3403", "gene99",
    "gene89", "gene2987", "gene43", "gene1925", "gene23", "gene1922",
    "gene3316", "gene33", "gene21", "gene97", "gene48", "gene54",
    "gene75", "gene81", "gene100", "gene26", "gene2561", "gene24",
    "gene68", "gene3043", "gene1450", "gene41", "gene658", "gene38",
    "gene77", "gene47", "gene60", "gene91", "gene2232", "gene50",
    "gene2322", "gene725", "gene3959", "gene3425", "gene652", "gene877",
    "gene5", "gene412", "gene1486", "gene30"
  ))
})


# ==============================================================================
# Test fdr argument
# ==============================================================================

test_that("Checking dbf() when fdr argument is set to 1e-20", {
  # Set verbosity to 0
  set_verbosity(0)
  
  #Create matrix containing 3 signatures
  m <- create_4_rnd_clust()
  
  res <- DBF(data=m,
             distance_method="pearson",
             k=75,
             row_sum=-Inf,
             highest=0.3,
             fdr = 1e-20,
             name = "test",
             output_path = ".")
  
  expect_equal(res@gene_clusters_metadata$cluster_id, 1)
  expect_equal(res@gene_clusters_metadata$number, "1")
  expect_equal(res@gene_clusters_metadata$size, 258)
  expect_equal(unlist(res@gene_clusters, use.names = F), c(
    "gene146", "gene189", "gene150", "gene117", "gene190", "gene135",
    "gene165", "gene186", "gene180", "gene155", "gene144", "gene132",
    "gene106", "gene192", "gene111", "gene153", "gene108", "gene159",
    "gene133", "gene166", "gene112", "gene143", "gene126", "gene145",
    "gene184", "gene122", "gene161", "gene176", "gene193", "gene137",
    "gene168", "gene160", "gene147", "gene107", "gene129", "gene188",
    "gene101", "gene104", "gene109", "gene114", "gene127", "gene157",
    "gene173", "gene197", "gene191", "gene177", "gene103", "gene105",
    "gene194", "gene163", "gene121", "gene116", "gene162", "gene158",
    "gene178", "gene175", "gene124", "gene141", "gene171", "gene128",
    "gene142", "gene198", "gene140", "gene119", "gene183", "gene167",
    "gene200", "gene199", "gene148", "gene174", "gene113", "gene151",
    "gene136", "gene179", "gene138", "gene181", "gene154", "gene130",
    "gene118", "gene115", "gene182", "gene134", "gene195", "gene164",
    "gene185", "gene120", "gene152", "gene149", "gene172", "gene131",
    "gene196", "gene110", "gene170", "gene125", "gene156", "gene123",
    "gene169", "gene102", "gene139", "gene187", "gene285", "gene273",
    "gene245", "gene272", "gene249", "gene230", "gene256", "gene225",
    "gene289", "gene286", "gene278", "gene282", "gene275", "gene214",
    "gene248", "gene277", "gene241", "gene206", "gene251", "gene298",
    "gene236", "gene267", "gene222", "gene290", "gene299", "gene223",
    "gene266", "gene217", "gene293", "gene229", "gene283", "gene300",
    "gene263", "gene235", "gene250", "gene212", "gene259", "gene219",
    "gene287", "gene233", "gene262", "gene239", "gene255", "gene258",
    "gene393", "gene203", "gene207", "gene240", "gene216", "gene232",
    "gene215", "gene253", "gene269", "gene237", "gene294", "gene390",
    "gene284", "gene247", "gene242", "gene312", "gene244", "gene297",
    "gene281", "gene226", "gene314", "gene1616", "gene76", "gene279",
    "gene316", "gene254", "gene246", "gene386", "gene364", "gene270",
    "gene369", "gene292", "gene318", "gene268", "gene288", "gene315",
    "gene398", "gene238", "gene387", "gene257", "gene363", "gene27",
    "gene37", "gene227", "gene220", "gene32", "gene234", "gene334",
    "gene838", "gene70", "gene202", "gene330", "gene55", "gene291",
    "gene208", "gene67", "gene320", "gene80", "gene3528", "gene382",
    "gene59", "gene326", "gene379", "gene16", "gene12", "gene84",
    "gene322", "gene205", "gene221", "gene329", "gene45", "gene295",
    "gene88", "gene271", "gene260", "gene224", "gene19", "gene201",
    "gene296", "gene324", "gene61", "gene211", "gene243", "gene349",
    "gene313", "gene306", "gene331", "gene280", "gene261", "gene368",
    "gene213", "gene209", "gene350", "gene78", "gene327", "gene3485",
    "gene73", "gene389", "gene319", "gene353", "gene36", "gene29",
    "gene397", "gene3991", "gene366", "gene39", "gene362", "gene1503",
    "gene7", "gene335", "gene2", "gene365", "gene57", "gene228"
  ))
})


# ==============================================================================
# Test no_dknn_filter argument
# ==============================================================================

test_that("Checking dbf() when no_dknn_filter argument is set to TRUE", {
  # Set verbosity to 0
  set_verbosity(0)
  
  #Create matrix containing 3 signatures
  m <- create_4_rnd_clust()
  
  res <- DBF(data=m,
             distance_method="pearson",
             k=75,
             row_sum=-Inf,
             highest=0.3,
             fdr = 1e-8,
             name = "test",
             output_path = ".",
             no_dknn_filter = TRUE)
  
  expect_equal(res@gene_clusters_metadata$cluster_id, 1)
  expect_equal(res@gene_clusters_metadata$number, "1")
  expect_equal(res@gene_clusters_metadata$size, 4000)
})
