# Set verbosity to 0
set_verbosity(0)

#Create matrix containing 3 signatures
m <- create_4_rnd_clust()

## A rather stringent version
res <- select_genes(data=m,
                    distance_method="kendall",
                    k=75,
                    row_sum=-Inf,
                    highest=0.3,
                    fdr = 1e-8)



test_that("Checking output slots generated by gene_clustering() using keep_nn as FALSE", {
  # Create output directory
  dir.create("tmp_dir")
  
  ## A rather stringent version
  res_no_keep_nn <- gene_clustering(object = res,
                                    inflation = 1.2,
                                    keep_nn = FALSE,
                                    k = 5,
                                    threads = 1,
                                    output_path = "tmp_dir")
  
  # =======================================================
  # Test name of temporary files
  expect_true(file.exists(file.path(res_no_keep_nn@parameters$output_path,
                                    paste0(res_no_keep_nn@parameters$name,
                                           ".input_mcl.txt"))))
  expect_true(file.exists(file.path(res_no_keep_nn@parameters$output_path,
                                    paste0(res_no_keep_nn@parameters$name,
                                           ".mcl_out.txt"))))
  # expect_false(file.exists(file.path(tempdir(), paste0(res_no_keep_nn@parameters$name,
  #                                                      ".input_mcl.txt"))))
  # expect_false(file.exists(file.path(tempdir(), paste0(res_no_keep_nn@parameters$name,
  #                                                      ".input_mcl.txt"))))
  expect_equal(length(res_no_keep_nn@parameters$name), 1)
  expect_that(res_no_keep_nn@parameters$name, is_a("character"))
  
  
  # =======================================================
  # Test matrix in res_no_keep_nn@data
  expect_equal(round(sum(res_no_keep_nn@data), 3), 2422.37)
  expect_equal(round(mean(res_no_keep_nn@data), 6), 0.337377)
  expect_equal(round(median(res_no_keep_nn@data), 6), 0.106821)
  expect_equal(round(sd(res_no_keep_nn@data), 6), 2.128261)
  
  expect_equal(round(sum(quantile(res_no_keep_nn@data)["0%"]), 6), -5.806817)
  expect_equal(round(sum(quantile(res_no_keep_nn@data)["25%"]), 6), -0.978668)
  expect_equal(round(sum(quantile(res_no_keep_nn@data)["50%"]), 6), 0.106821)
  expect_equal(round(sum(quantile(res_no_keep_nn@data)["75%"]), 6), 1.40248)
  expect_equal(round(sum(quantile(res_no_keep_nn@data)["100%"]), 6), 7.073935)
  
  expect_equal(round(sum(colMeans(res_no_keep_nn@data)), 5), 6.74755)
  expect_equal(round(sum(rowMeans(res_no_keep_nn@data)), 4), 121.1185)
  
  expect_equal(ncol(res_no_keep_nn@data), 20)
  expect_equal(colnames(res_no_keep_nn@data), paste0("sample", seq(1, 20)))
  
  expect_equal(nrow(res_no_keep_nn@data), 359)
  
  expect_equal(nrow(res_no_keep_nn@data), length(get_genes(res_no_keep_nn)))
  expect_equal(rownames(res_no_keep_nn@data), get_genes(res_no_keep_nn))
  expect_equal(rownames(res_no_keep_nn@data), unlist(res_no_keep_nn@gene_clusters, use.names = F))
  expect_equal(nrow(res_no_keep_nn@data), length(get_genes(res_no_keep_nn)))
  expect_equal(nrow(res_no_keep_nn@data), length(unlist(res_no_keep_nn@gene_clusters)))
  
  expect_equal(round(sum(res_no_keep_nn@data^2), 2), 33334.51)
  
  expect_that(res_no_keep_nn@data, is_a("matrix"))
  
  expect_equal(length(res_no_keep_nn@data), 7180)
  
  
  # =======================================================
  # Test observed distances in res_no_keep_nn@dbf_output$dknn
  expect_equal(round(sum(res_no_keep_nn@dbf_output$dknn), 3), 1315.337)
  expect_equal(round(mean(res_no_keep_nn@dbf_output$dknn), 7), 0.3288342)
  expect_equal(round(median(res_no_keep_nn@dbf_output$dknn), 7), 0.3315789)
  expect_equal(round(sd(res_no_keep_nn@dbf_output$dknn), 6), 0.013926)
  
  expect_equal(round(sum(quantile(res_no_keep_nn@dbf_output$dknn)["0%"]), 6), 0.252632)
  expect_equal(round(sum(quantile(res_no_keep_nn@dbf_output$dknn)["25%"]), 6), 0.326316)
  expect_equal(round(sum(quantile(res_no_keep_nn@dbf_output$dknn)["50%"]), 6), 0.331579)
  expect_equal(round(sum(quantile(res_no_keep_nn@dbf_output$dknn)["75%"]), 6), 0.336842)
  expect_equal(round(sum(quantile(res_no_keep_nn@dbf_output$dknn)["100%"]), 6), 0.347368)
  
  expect_equal(length(res_no_keep_nn@dbf_output$dknn), 4000)
  
  expect_equal(round(sum(res_no_keep_nn@dbf_output$dknn^2), 2), 433.3)
  
  expect_that(res_no_keep_nn@dbf_output$dknn, is_a("numeric"))
  
  
  # =======================================================
  # Test simulated distances in res_no_keep_nn@dbf_output$simulated_dknn
  expect_equal(round(sum(res_no_keep_nn@dbf_output$simulated_dknn), 3), 1348.411)
  expect_equal(round(mean(res_no_keep_nn@dbf_output$simulated_dknn), 7), 0.3371026)
  expect_equal(round(median(res_no_keep_nn@dbf_output$simulated_dknn), 7), 0.3368421)
  expect_equal(round(sd(res_no_keep_nn@dbf_output$simulated_dknn), 6), 0.003783)
  
  expect_equal(round(sum(quantile(res_no_keep_nn@dbf_output$simulated_dknn)["0%"]), 6), 0.326316)
  expect_equal(round(sum(quantile(res_no_keep_nn@dbf_output$simulated_dknn)["25%"]), 6), 0.336842)
  expect_equal(round(sum(quantile(res_no_keep_nn@dbf_output$simulated_dknn)["50%"]), 6), 0.336842)
  expect_equal(round(sum(quantile(res_no_keep_nn@dbf_output$simulated_dknn)["75%"]), 6), 0.336842)
  expect_equal(round(sum(quantile(res_no_keep_nn@dbf_output$simulated_dknn)["100%"]), 6), 0.347368)
  
  expect_equal(length(res_no_keep_nn@dbf_output$simulated_dknn), 4000)
  
  expect_equal(round(sum(res_no_keep_nn@dbf_output$simulated_dknn^2), 2), 454.61)
  
  expect_that(res_no_keep_nn@dbf_output$simulated_dknn, is_a("numeric"))
  
  
  # =======================================================
  # Test critical distance in res_no_keep_nn@critical_distance
  expect_equal(round(res_no_keep_nn@dbf_output$critical_distance, 7), 0.3157895)
  expect_that(res_no_keep_nn@dbf_output$critical_distance, is_a("numeric"))
  expect_equal(length(res_no_keep_nn@dbf_output$critical_distance), 1)
  
  
  # =======================================================
  # Test gene clusters in res_no_keep_nn@gene_clusters
  expect_equal(sum(as.numeric(names(res_no_keep_nn@gene_clusters))), 10)
  expect_equal(names(res_no_keep_nn@gene_clusters), c("1", "2", "3", "4"))
  expect_equal(length(unlist(res_no_keep_nn@gene_clusters)), 359)
  expect_equal(length(unlist(res_no_keep_nn@gene_clusters$`1`)), 123)
  expect_equal(length(unlist(res_no_keep_nn@gene_clusters$`2`)), 88)
  expect_equal(length(unlist(res_no_keep_nn@gene_clusters$`3`)), 81)
  expect_equal(length(unlist(res_no_keep_nn@gene_clusters$`4`)), 67)
  
  expect_equal(unlist(res_no_keep_nn@gene_clusters, use.names = F), get_genes(res_no_keep_nn))
  expect_equal(
    unlist(res_no_keep_nn@gene_clusters$`1`, use.names = F),
    get_genes(res_no_keep_nn, cluster = 1)
  )
  expect_equal(
    unlist(res_no_keep_nn@gene_clusters$`2`, use.names = F),
    get_genes(res_no_keep_nn, cluster = 2)
  )
  expect_equal(
    unlist(res_no_keep_nn@gene_clusters$`3`, use.names = F),
    get_genes(res_no_keep_nn, cluster = 3)
  )
  expect_equal(
    unlist(res_no_keep_nn@gene_clusters$`4`, use.names = F),
    get_genes(res_no_keep_nn, cluster = 4)
  )
  expect_equal(unlist(res_no_keep_nn@gene_clusters, use.names = F), rownames(res_no_keep_nn@data))
  
  expect_that(res_no_keep_nn@gene_clusters, is_a("list"))
  expect_that(res_no_keep_nn@gene_clusters$`1`, is_a("character"))
  
  
  # =======================================================
  # Test size of gene clusters in res_no_keep_nn@gene_clusters_metadata$size
  expect_equal(res_no_keep_nn@gene_clusters_metadata$size, c(
    "1" = 123,
    "2" = 88,
    "3" = 81,
    "4" = 67
  ))
  expect_that(res_no_keep_nn@gene_clusters_metadata$size, is_a("integer"))
  expect_equal(max(res_no_keep_nn@gene_clusters_metadata$size), 123)
  expect_equal(min(res_no_keep_nn@gene_clusters_metadata$size), 67)
  expect_equal(length(res_no_keep_nn@gene_clusters_metadata$size), 4)
  
  expect_equal(
    res_no_keep_nn@gene_clusters_metadata$size[1],
    c("1" = length(res_no_keep_nn@gene_clusters$`1`))
  )
  expect_equal(
    res_no_keep_nn@gene_clusters_metadata$size[2],
    c("2" = length(res_no_keep_nn@gene_clusters$`2`))
  )
  expect_equal(
    res_no_keep_nn@gene_clusters_metadata$size[3],
    c("3" = length(res_no_keep_nn@gene_clusters$`3`))
  )
  expect_equal(
    res_no_keep_nn@gene_clusters_metadata$size[4],
    c("4" = length(res_no_keep_nn@gene_clusters$`4`))
  )
  expect_equal(
    res_no_keep_nn@gene_clusters_metadata$size[1],
    c("1" = length(get_genes(res_no_keep_nn, cluster = 1)))
  )
  expect_equal(
    res_no_keep_nn@gene_clusters_metadata$size[2],
    c("2" = length(get_genes(res_no_keep_nn, cluster = 2)))
  )
  expect_equal(
    res_no_keep_nn@gene_clusters_metadata$size[3],
    c("3" = length(get_genes(res_no_keep_nn, cluster = 3)))
  )
  expect_equal(
    res_no_keep_nn@gene_clusters_metadata$size[4],
    c("4" = length(get_genes(res_no_keep_nn, cluster = 4)))
  )
  
  
  # =======================================================
  # Test parameters in res_no_keep_nn@parameters
  expect_that(res_no_keep_nn@parameters, is_a("list"))
  expect_equal(length(res_no_keep_nn@parameters), 12)
  expect_equal(names(res_no_keep_nn@parameters), c(
    "distance_method",
    "k",
    "highest",
    "fdr",
    "row_sum",
    "no_dknn_filter",
    "seed",
    "keep_nn",
    "k_mcl_graph",
    "output_path",
    "name",
    "inflation"
  ))
  
  expect_equal(res_no_keep_nn@parameters$output_path, "tmp_dir")
  expect_that(res_no_keep_nn@parameters$output_path, is_a("character"))
  expect_equal(length(res_no_keep_nn@parameters$output_path), 1)
  
  expect_that(res_no_keep_nn@parameters$name, is_a("character"))
  expect_equal(length(res_no_keep_nn@parameters$name), 1)
  expect_equal(nchar(res_no_keep_nn@parameters$name), 10)
  expect_true(grepl("[[:alnum:]]+", res_no_keep_nn@parameters$name))
  
  expect_equal(res_no_keep_nn@parameters$distance_method, "kendall")
  expect_that(res_no_keep_nn@parameters$distance_method, is_a("character"))
  expect_equal(length(res_no_keep_nn@parameters$distance_method), 1)
  
  expect_equal(res_no_keep_nn@parameters$k, 75)
  expect_that(res_no_keep_nn@parameters$k, is_a("numeric"))
  expect_equal(length(res_no_keep_nn@parameters$k), 1)
  
  expect_equal(res_no_keep_nn@parameters$highest, 0.3)
  expect_that(res_no_keep_nn@parameters$highest, is_a("numeric"))
  expect_equal(length(res_no_keep_nn@parameters$highest), 1)
  
  expect_equal(res_no_keep_nn@parameters$fdr, 1e-08)
  expect_that(res_no_keep_nn@parameters$fdr, is_a("numeric"))
  expect_equal(length(res_no_keep_nn@parameters$fdr), 1)
  
  expect_equal(res_no_keep_nn@parameters$row_sum, -Inf)
  expect_that(res_no_keep_nn@parameters$row_sum, is_a("numeric"))
  expect_equal(length(res_no_keep_nn@parameters$row_sum), 1)
  
  expect_false(res_no_keep_nn@parameters$no_dknn_filter)
  
  expect_equal(res_no_keep_nn@parameters$seed, 123)
  expect_that(res_no_keep_nn@parameters$seed, is_a("numeric"))
  expect_equal(length(res_no_keep_nn@parameters$seed), 1)
  
  expect_false(res_no_keep_nn@parameters$keep_nn)
  
  expect_equal(res_no_keep_nn@parameters$k_mcl_graph, 5)
  expect_that(res_no_keep_nn@parameters$k_mcl_graph, is_a("numeric"))
  expect_equal(length(res_no_keep_nn@parameters$k_mcl_graph), 1)
  
  expect_equal(res_no_keep_nn@parameters$inflation, 1.2)
  expect_that(res_no_keep_nn@parameters$inflation, is_a("numeric"))
  expect_equal(length(res_no_keep_nn@parameters$inflation), 1)
  
  
  # =======================================================
  # Test parameters in res_no_keep_nn@cluster_number
  expect_equal(res_no_keep_nn@gene_clusters_metadata$number, 4)
  expect_that(res_no_keep_nn@gene_clusters_metadata$number, is_a("numeric"))
  
  
  # =======================================================
  # Test parameters in res_no_keep_nn@cluster_list
  expect_equal(length(res_no_keep_nn@gene_clusters_metadata$cluster_id), 4)
  expect_equal(res_no_keep_nn@gene_clusters_metadata$cluster_id, seq(1, 4, 1))
  expect_that(res_no_keep_nn@gene_clusters_metadata$cluster_id, is_a("numeric"))
  
  # Remove temporary files
  unlink("tmp_dir", recursive = TRUE)
})




test_that("Checking output slots generated by gene_clsutering() using keep_nn as TRUE", {
  ## A rather stringent version
  res_keep_nn <- gene_clustering(object = res,
                                 inflation = 1.2,
                                 keep_nn = TRUE,
                                 threads = 1,
                                 name = "test")
  
  # =======================================================
  # Test name of temporary files
  expect_equal(res_keep_nn@parameters$name, "test")
  expect_true(file.exists(file.path(res_keep_nn@parameters$output_path,
                                    paste0(res_keep_nn@parameters$name,
                                           ".input_mcl.txt"))))
  expect_true(file.exists(file.path(res_keep_nn@parameters$output_path,
                                    paste0(res_keep_nn@parameters$name,
                                           ".mcl_out.txt"))))
  expect_true(file.exists(file.path(tempdir(), paste0(res_keep_nn@parameters$name,
                                                       ".input_mcl.txt"))))
  expect_true(file.exists(file.path(tempdir(), paste0(res_keep_nn@parameters$name,
                                                       ".input_mcl.txt"))))
  expect_equal(length(res_keep_nn@parameters$name), 1)
  expect_that(res_keep_nn@parameters$name, is_a("character"))
  
  
  # =======================================================
  # Test matrix in res_keep_nn@data
  expect_equal(round(sum(res_keep_nn@data), 3), 2422.37)
  expect_equal(round(mean(res_keep_nn@data), 6), 0.337377)
  expect_equal(round(median(res_keep_nn@data), 6), 0.106821)
  expect_equal(round(sd(res_keep_nn@data), 6), 2.128261)
  
  expect_equal(round(sum(quantile(res_keep_nn@data)["0%"]), 6), -5.806817)
  expect_equal(round(sum(quantile(res_keep_nn@data)["25%"]), 6), -0.978668)
  expect_equal(round(sum(quantile(res_keep_nn@data)["50%"]), 6), 0.106821)
  expect_equal(round(sum(quantile(res_keep_nn@data)["75%"]), 6), 1.40248)
  expect_equal(round(sum(quantile(res_keep_nn@data)["100%"]), 6), 7.073935)
  
  expect_equal(round(sum(colMeans(res_keep_nn@data)), 5), 6.74755)
  expect_equal(round(sum(rowMeans(res_keep_nn@data)), 4), 121.1185)
  
  expect_equal(ncol(res_keep_nn@data), 20)
  expect_equal(colnames(res_keep_nn@data), paste0("sample", seq(1, 20)))
  
  expect_equal(nrow(res_keep_nn@data), 359)
  
  expect_equal(nrow(res_keep_nn@data), length(get_genes(res_keep_nn)))
  expect_equal(rownames(res_keep_nn@data), get_genes(res_keep_nn))
  expect_equal(rownames(res_keep_nn@data), unlist(res_keep_nn@gene_clusters, use.names = F))
  expect_equal(nrow(res_keep_nn@data), length(get_genes(res_keep_nn)))
  expect_equal(nrow(res_keep_nn@data), length(unlist(res_keep_nn@gene_clusters)))
  
  expect_equal(round(sum(res_keep_nn@data^2), 2), 33334.51)
  
  expect_that(res_keep_nn@data, is_a("matrix"))
  
  expect_equal(length(res_keep_nn@data), 7180)
  
  
  # =======================================================
  # Test observed distances in res_keep_nn@dbf_output$dknn
  expect_equal(round(sum(res_keep_nn@dbf_output$dknn), 3), 1315.337)
  expect_equal(round(mean(res_keep_nn@dbf_output$dknn), 7), 0.3288342)
  expect_equal(round(median(res_keep_nn@dbf_output$dknn), 7), 0.3315789)
  expect_equal(round(sd(res_keep_nn@dbf_output$dknn), 6), 0.013926)
  
  expect_equal(round(sum(quantile(res_keep_nn@dbf_output$dknn)["0%"]), 6), 0.252632)
  expect_equal(round(sum(quantile(res_keep_nn@dbf_output$dknn)["25%"]), 6), 0.326316)
  expect_equal(round(sum(quantile(res_keep_nn@dbf_output$dknn)["50%"]), 6), 0.331579)
  expect_equal(round(sum(quantile(res_keep_nn@dbf_output$dknn)["75%"]), 6), 0.336842)
  expect_equal(round(sum(quantile(res_keep_nn@dbf_output$dknn)["100%"]), 6), 0.347368)
  
  expect_equal(length(res_keep_nn@dbf_output$dknn), 4000)
  
  expect_equal(round(sum(res_keep_nn@dbf_output$dknn^2), 2), 433.3)
  
  expect_that(res_keep_nn@dbf_output$dknn, is_a("numeric"))
  
  
  # =======================================================
  # Test simulated distances in res_keep_nn@dbf_output$simulated_dknn
  expect_equal(round(sum(res_keep_nn@dbf_output$simulated_dknn), 3), 1348.411)
  expect_equal(round(mean(res_keep_nn@dbf_output$simulated_dknn), 7), 0.3371026)
  expect_equal(round(median(res_keep_nn@dbf_output$simulated_dknn), 7), 0.3368421)
  expect_equal(round(sd(res_keep_nn@dbf_output$simulated_dknn), 6), 0.003783)
  
  expect_equal(round(sum(quantile(res_keep_nn@dbf_output$simulated_dknn)["0%"]), 6), 0.326316)
  expect_equal(round(sum(quantile(res_keep_nn@dbf_output$simulated_dknn)["25%"]), 6), 0.336842)
  expect_equal(round(sum(quantile(res_keep_nn@dbf_output$simulated_dknn)["50%"]), 6), 0.336842)
  expect_equal(round(sum(quantile(res_keep_nn@dbf_output$simulated_dknn)["75%"]), 6), 0.336842)
  expect_equal(round(sum(quantile(res_keep_nn@dbf_output$simulated_dknn)["100%"]), 6), 0.347368)
  
  expect_equal(length(res_keep_nn@dbf_output$simulated_dknn), 4000)
  
  expect_equal(round(sum(res_keep_nn@dbf_output$simulated_dknn^2), 2), 454.61)
  
  expect_that(res_keep_nn@dbf_output$simulated_dknn, is_a("numeric"))
  
  
  # =======================================================
  # Test critical distance in res_keep_nn@critical_distance
  expect_equal(round(res_keep_nn@dbf_output$critical_distance, 7), 0.3157895)
  expect_that(res_keep_nn@dbf_output$critical_distance, is_a("numeric"))
  expect_equal(length(res_keep_nn@dbf_output$critical_distance), 1)
  
  
  # =======================================================
  # Test gene clusters in res_keep_nn@gene_clusters
  expect_equal(sum(as.numeric(names(res_keep_nn@gene_clusters))), 10)
  expect_equal(names(res_keep_nn@gene_clusters), c("1", "2", "3", "4"))
  expect_equal(length(unlist(res_keep_nn@gene_clusters)), 359)
  expect_equal(length(unlist(res_keep_nn@gene_clusters$`1`)), 119)
  expect_equal(length(unlist(res_keep_nn@gene_clusters$`2`)), 90)
  expect_equal(length(unlist(res_keep_nn@gene_clusters$`3`)), 83)
  expect_equal(length(unlist(res_keep_nn@gene_clusters$`4`)), 67)
  
  expect_equal(unlist(res_keep_nn@gene_clusters, use.names = F), get_genes(res_keep_nn))
  expect_equal(
    unlist(res_keep_nn@gene_clusters$`1`, use.names = F),
    get_genes(res_keep_nn, cluster = 1)
  )
  expect_equal(
    unlist(res_keep_nn@gene_clusters$`2`, use.names = F),
    get_genes(res_keep_nn, cluster = 2)
  )
  expect_equal(
    unlist(res_keep_nn@gene_clusters$`3`, use.names = F),
    get_genes(res_keep_nn, cluster = 3)
  )
  expect_equal(
    unlist(res_keep_nn@gene_clusters$`4`, use.names = F),
    get_genes(res_keep_nn, cluster = 4)
  )
  expect_equal(unlist(res_keep_nn@gene_clusters, use.names = F), rownames(res_keep_nn@data))
  
  expect_that(res_keep_nn@gene_clusters, is_a("list"))
  expect_that(res_keep_nn@gene_clusters$`1`, is_a("character"))
  
  
  # =======================================================
  # Test size of gene clusters in res_keep_nn@gene_clusters_metadata$size
  expect_equal(res_keep_nn@gene_clusters_metadata$size, c(
    "1" = 119,
    "2" = 90,
    "3" = 83,
    "4" = 67
  ))
  expect_that(res_keep_nn@gene_clusters_metadata$size, is_a("integer"))
  expect_equal(max(res_keep_nn@gene_clusters_metadata$size), 119)
  expect_equal(min(res_keep_nn@gene_clusters_metadata$size), 67)
  expect_equal(length(res_keep_nn@gene_clusters_metadata$size), 4)
  
  expect_equal(
    res_keep_nn@gene_clusters_metadata$size[1],
    c("1" = length(res_keep_nn@gene_clusters$`1`))
  )
  expect_equal(
    res_keep_nn@gene_clusters_metadata$size[2],
    c("2" = length(res_keep_nn@gene_clusters$`2`))
  )
  expect_equal(
    res_keep_nn@gene_clusters_metadata$size[3],
    c("3" = length(res_keep_nn@gene_clusters$`3`))
  )
  expect_equal(
    res_keep_nn@gene_clusters_metadata$size[4],
    c("4" = length(res_keep_nn@gene_clusters$`4`))
  )
  expect_equal(
    res_keep_nn@gene_clusters_metadata$size[1],
    c("1" = length(get_genes(res_keep_nn, cluster = 1)))
  )
  expect_equal(
    res_keep_nn@gene_clusters_metadata$size[2],
    c("2" = length(get_genes(res_keep_nn, cluster = 2)))
  )
  expect_equal(
    res_keep_nn@gene_clusters_metadata$size[3],
    c("3" = length(get_genes(res_keep_nn, cluster = 3)))
  )
  expect_equal(
    res_keep_nn@gene_clusters_metadata$size[4],
    c("4" = length(get_genes(res_keep_nn, cluster = 4)))
  )
  
  
  # =======================================================
  # Test parameters in res_keep_nn@parameters
  expect_that(res_keep_nn@parameters, is_a("list"))
  expect_equal(length(res_keep_nn@parameters), 11)
  expect_equal(names(res_keep_nn@parameters), c(
    "distance_method",
    "k",
    "highest",
    "fdr",
    "row_sum",
    "no_dknn_filter",
    "seed",
    "keep_nn",
    "output_path",
    "name",
    "inflation"
  ))
  
  expect_that(res_keep_nn@parameters$output_path, is_a("character"))
  expect_equal(length(res_keep_nn@parameters$output_path), 1)
  
  expect_equal(res_keep_nn@parameters$name, "test")
  expect_that(res_keep_nn@parameters$name, is_a("character"))
  expect_equal(length(res_keep_nn@parameters$name), 1)
  
  expect_equal(res_keep_nn@parameters$distance_method, "kendall")
  expect_that(res_keep_nn@parameters$distance_method, is_a("character"))
  expect_equal(length(res_keep_nn@parameters$distance_method), 1)
  
  expect_equal(res_keep_nn@parameters$k, 75)
  expect_that(res_keep_nn@parameters$k, is_a("numeric"))
  expect_equal(length(res_keep_nn@parameters$k), 1)
  
  expect_equal(res_keep_nn@parameters$highest, 0.3)
  expect_that(res_keep_nn@parameters$highest, is_a("numeric"))
  expect_equal(length(res_keep_nn@parameters$highest), 1)
  
  expect_equal(res_keep_nn@parameters$fdr, 1e-08)
  expect_that(res_keep_nn@parameters$fdr, is_a("numeric"))
  expect_equal(length(res_keep_nn@parameters$fdr), 1)
  
  expect_equal(res_keep_nn@parameters$row_sum, -Inf)
  expect_that(res_keep_nn@parameters$row_sum, is_a("numeric"))
  expect_equal(length(res_keep_nn@parameters$row_sum), 1)
  
  expect_false(res_keep_nn@parameters$no_dknn_filter)
  
  expect_equal(res_keep_nn@parameters$seed, 123)
  expect_that(res_keep_nn@parameters$seed, is_a("numeric"))
  expect_equal(length(res_keep_nn@parameters$seed), 1)
  
  expect_true(res_keep_nn@parameters$keep_nn)
  
  expect_equal(res_keep_nn@parameters$inflation, 1.2)
  expect_that(res_keep_nn@parameters$inflation, is_a("numeric"))
  expect_equal(length(res_keep_nn@parameters$inflation), 1)
  
  
  # =======================================================
  # Test parameters in res_keep_nn@cluster_number
  expect_equal(res_keep_nn@gene_clusters_metadata$number, 4)
  expect_that(res_keep_nn@gene_clusters_metadata$number, is_a("numeric"))
  
  
  # =======================================================
  # Test parameters in res_keep_nn@cluster_list
  expect_equal(length(res_keep_nn@gene_clusters_metadata$cluster_id), 4)
  expect_equal(res_keep_nn@gene_clusters_metadata$cluster_id, seq(1, 4, 1))
  expect_that(res_keep_nn@gene_clusters_metadata$cluster_id, is_a("numeric"))
})





# ==============================================================================
# Test output_path argument
# ==============================================================================

test_that("Checking stop if output directory provided does not exist", {
  expect_error(gene_clustering(data = m,
                               name = "test",
                               inflation = 2,
                               output_path = "not_a_directory"))
})
