test_that("Test messages when looking at ClusterSet object", {
  obj <- new("ClusterSet")
  msg_clusterset <- capture.output(obj)
  
  expect_equal(msg_clusterset[1], "\t\tAn object of class ClusterSet")
  expect_equal(msg_clusterset[2], "\t\tName: ")
  expect_equal(msg_clusterset[3], "\t\tMemory used:  2520 ")
  expect_equal(msg_clusterset[4], "\t\tNumber of cells:  0 ")
  expect_equal(msg_clusterset[5], "\t\tNumber of informative genes:  0 ")
  expect_equal(msg_clusterset[6], "\t\tNumber of gene clusters:  ")
  expect_equal(msg_clusterset[7], "\t\tThis object contains the following informations:")
  expect_equal(msg_clusterset[8], "\t\t\t -  data ")
  expect_equal(msg_clusterset[9], "\t\t\t -  gene_clusters ")
  expect_equal(msg_clusterset[10], "\t\t\t -  top_genes ")
  expect_equal(msg_clusterset[11], "\t\t\t -  gene_clusters_metadata ")
  expect_equal(msg_clusterset[12], "\t\t\t -  gene_cluster_annotations ")
  expect_equal(msg_clusterset[13], "\t\t\t -  cells_metadata ")
  expect_equal(msg_clusterset[14], "\t\t\t -  dbf_output ")
  expect_equal(msg_clusterset[15], "\t\t\t -  parameters ")
  
})
