set_verbosity(0)

test_that("Checking output slots generated by find_gene_clusters...", {
  # Create matrix containing 4 signatures
  m <- create_4_rnd_clust()

  ## A rather stringent version
  res <- find_gene_clusters(
    data = m,
    name = "test",
    distance_method = "pearson",
    inflation = 2,
    k = 75,
    row_sum = -Inf,
    highest = 0.3,
    min_nb_supporting_cell = 0,
    fdr = 1e-8,
    output_path = tempdir()
  )

  # =======================================================
  # Test name of temporary files
  expect_equal(res@parameters$filename, "test")
  expect_false(file.exists(file.path(tempdir(), "test.dbf_out.txt")))
  expect_false(file.exists(file.path(tempdir(), "test.mcl_out.txt")))
  expect_equal(length(res@parameters$filename), 1)
  expect_that(res@parameters$filename, is_a("character"))


  # =======================================================
  # Test matrix in res@data
  expect_equal(round(sum(res@data), 3), 2146.661)
  expect_equal(round(mean(res@data), 6), 0.312924)
  expect_equal(round(median(res@data), 6), 0.090583)
  expect_equal(round(sd(res@data), 6), 2.181212)

  expect_equal(round(sum(quantile(res@data)["0%"]), 6), -5.806817)
  expect_equal(round(sum(quantile(res@data)["25%"]), 6), -1.056961)
  expect_equal(round(sum(quantile(res@data)["50%"]), 6), 0.090583)
  expect_equal(round(sum(quantile(res@data)["75%"]), 6), 1.437996)
  expect_equal(round(sum(quantile(res@data)["100%"]), 6), 7.073935)

  expect_equal(round(sum(colMeans(res@data)), 5), 6.25849)
  expect_equal(round(sum(rowMeans(res@data)), 4), 107.3331)

  expect_equal(round(max(res@data), 6), 7.073935)

  expect_equal(ncol(res@data), 20)
  expect_equal(colnames(res@data), paste0("sample", seq(1, 20)))

  expect_equal(nrow(res@data), 343)

  expect_equal(nrow(res@data), length(get_genes(res)))
  expect_equal(rownames(res@data), get_genes(res))
  expect_equal(rownames(res@data), unlist(res@gene_clusters, use.names = F))
  expect_equal(nrow(res@data), length(get_genes(res)))
  expect_equal(nrow(res@data), length(unlist(res@gene_clusters)))

  expect_equal(round(sum(res@data^2), 2), 33304.7)

  expect_that(res@data, is_a("matrix"))

  expect_equal(length(res@data), 6860)


  # =======================================================
  # Test observed distances in res@dbf_output$dknn
  expect_equal(round(sum(res@dbf_output$dknn), 3), 2070.863)
  expect_equal(round(mean(res@dbf_output$dknn), 7), 0.5177157)
  expect_equal(round(median(res@dbf_output$dknn), 7), 0.5333734)
  expect_equal(round(sd(res@dbf_output$dknn), 6), 0.058557)

  expect_equal(round(sum(quantile(res@dbf_output$dknn)["0%"]), 6), 0.151747)
  expect_equal(round(sum(quantile(res@dbf_output$dknn)["25%"]), 6), 0.52163)
  expect_equal(round(sum(quantile(res@dbf_output$dknn)["50%"]), 6), 0.533373)
  expect_equal(round(sum(quantile(res@dbf_output$dknn)["75%"]), 6), 0.541248)
  expect_equal(round(sum(quantile(res@dbf_output$dknn)["100%"]), 6), 0.569402)

  expect_equal(length(res@dbf_output$dknn), 4000)

  expect_equal(round(sum(res@dbf_output$dknn^2), 2), 1085.83)

  expect_that(res@dbf_output$dknn, is_a("numeric"))


  # =======================================================
  # Test simulated distances in res@dbf_output$simulated_dknn
  expect_equal(round(sum(res@dbf_output$simulated_dknn), 3), 2153.312)
  expect_equal(round(mean(res@dbf_output$simulated_dknn), 7), 0.538328)
  expect_equal(round(median(res@dbf_output$simulated_dknn), 7), 0.538304)
  expect_equal(round(sd(res@dbf_output$simulated_dknn), 6), 0.009098)

  expect_equal(
    round(sum(quantile(res@dbf_output$simulated_dknn)["0%"]), 6),
    0.504041
  )
  expect_equal(
    round(sum(quantile(res@dbf_output$simulated_dknn)["25%"]), 6),
    0.532663
  )
  expect_equal(
    round(sum(quantile(res@dbf_output$simulated_dknn)["50%"]), 6),
    0.538304
  )
  expect_equal(
    round(sum(quantile(res@dbf_output$simulated_dknn)["75%"]), 6),
    0.544447
  )
  expect_equal(
    round(sum(quantile(res@dbf_output$simulated_dknn)["100%"]), 6),
    0.572353
  )

  expect_equal(length(res@dbf_output$simulated_dknn), 4000)

  expect_equal(round(sum(res@dbf_output$simulated_dknn^2), 2), 1159.52)

  expect_that(res@dbf_output$simulated_dknn, is_a("numeric"))


  # =======================================================
  # Test critical distance in res@critical_distance
  expect_equal(round(res@dbf_output$critical_distance, 7), 0.4772475)
  expect_that(res@dbf_output$critical_distance, is_a("numeric"))
  expect_equal(length(res@dbf_output$critical_distance), 1)


  # =======================================================
  # Test gene clusters in res@gene_clusters
  expect_equal(sum(as.numeric(names(res@gene_clusters))), 10)
  expect_equal(names(res@gene_clusters), c("1", "2", "3", "4"))
  expect_equal(length(unlist(res@gene_clusters)), 343)
  expect_equal(length(unlist(res@gene_clusters$`1`)), 104)
  expect_equal(length(unlist(res@gene_clusters$`2`)), 99)
  expect_equal(length(unlist(res@gene_clusters$`3`)), 76)
  expect_equal(length(unlist(res@gene_clusters$`4`)), 64)

  expect_equal(unlist(res@gene_clusters, use.names = F), get_genes(res))
  expect_equal(
    unlist(res@gene_clusters$`1`, use.names = F),
    get_genes(res, cluster = 1)
  )
  expect_equal(
    unlist(res@gene_clusters$`2`, use.names = F),
    get_genes(res, cluster = 2)
  )
  expect_equal(
    unlist(res@gene_clusters$`3`, use.names = F),
    get_genes(res, cluster = 3)
  )
  expect_equal(
    unlist(res@gene_clusters$`4`, use.names = F),
    get_genes(res, cluster = 4)
  )
  expect_equal(unlist(res@gene_clusters, use.names = F), rownames(res@data))

  expect_that(res@gene_clusters, is_a("list"))
  expect_that(res@gene_clusters$`1`, is_a("character"))


  # =======================================================
  # Test size of gene clusters in res@gene_clusters_metadata$size
  expect_equal(res@gene_clusters_metadata$size, c(
    "1" = 104,
    "2" = 99,
    "3" = 76,
    "4" = 64
  ))
  expect_that(res@gene_clusters_metadata$size, is_a("integer"))
  expect_equal(max(res@gene_clusters_metadata$size), 104)
  expect_equal(min(res@gene_clusters_metadata$size), 64)
  expect_equal(length(res@gene_clusters_metadata$size), 4)

  expect_equal(
    res@gene_clusters_metadata$size[1],
    c("1" = length(res@gene_clusters$`1`))
  )
  expect_equal(
    res@gene_clusters_metadata$size[2],
    c("2" = length(res@gene_clusters$`2`))
  )
  expect_equal(
    res@gene_clusters_metadata$size[3],
    c("3" = length(res@gene_clusters$`3`))
  )
  expect_equal(
    res@gene_clusters_metadata$size[4],
    c("4" = length(res@gene_clusters$`4`))
  )
  expect_equal(
    res@gene_clusters_metadata$size[1],
    c("1" = length(get_genes(res, cluster = 1)))
  )
  expect_equal(
    res@gene_clusters_metadata$size[2],
    c("2" = length(get_genes(res, cluster = 2)))
  )
  expect_equal(
    res@gene_clusters_metadata$size[3],
    c("3" = length(get_genes(res, cluster = 3)))
  )
  expect_equal(
    res@gene_clusters_metadata$size[4],
    c("4" = length(get_genes(res, cluster = 4)))
  )


  # =======================================================
  # Test parameters in res@parameters
  expect_that(res@parameters, is_a("list"))
  expect_equal(length(res@parameters), 11)
  expect_equal(names(res@parameters), c(
    "filename",
    "distance_method",
    "k",
    "inflation",
    "highest",
    "fdr",
    "min_nb_supporting_cell",
    "min_pct_gene_expressed",
    "min_cluster_size",
    "row_sum",
    "seed"
  ))

  expect_equal(res@parameters$distance_method, "pearson")
  expect_that(res@parameters$distance_method, is_a("character"))
  expect_equal(length(res@parameters$distance_method), 1)

  expect_equal(res@parameters$k, 75)
  expect_that(res@parameters$k, is_a("numeric"))
  expect_equal(length(res@parameters$k), 1)

  expect_equal(res@parameters$inflation, 2)
  expect_that(res@parameters$inflation, is_a("numeric"))
  expect_equal(length(res@parameters$inflation), 1)

  expect_equal(res@parameters$highest, 0.3)
  expect_that(res@parameters$highest, is_a("numeric"))
  expect_equal(length(res@parameters$highest), 1)

  expect_equal(res@parameters$fdr, 1e-08)
  expect_that(res@parameters$fdr, is_a("numeric"))
  expect_equal(length(res@parameters$fdr), 1)

  expect_equal(res@parameters$min_nb_supporting_cell, 0)
  expect_that(res@parameters$min_nb_supporting_cell, is_a("numeric"))
  expect_equal(length(res@parameters$min_nb_supporting_cell), 1)

  expect_equal(res@parameters$min_pct_gene_expressed, 40)
  expect_that(res@parameters$min_pct_gene_expressed, is_a("numeric"))
  expect_equal(length(res@parameters$min_pct_gene_expressed), 1)

  expect_equal(res@parameters$min_cluster_size, 10)
  expect_that(res@parameters$min_cluster_size, is_a("numeric"))
  expect_equal(length(res@parameters$min_cluster_size), 1)

  expect_equal(res@parameters$row_sum, -Inf)
  expect_that(res@parameters$row_sum, is_a("numeric"))
  expect_equal(length(res@parameters$row_sum), 1)

  expect_equal(res@parameters$seed, 123)
  expect_that(res@parameters$seed, is_a("numeric"))
  expect_equal(length(res@parameters$seed), 1)


  # =======================================================
  # Test parameters in res@cluster_number
  expect_equal(res@gene_clusters_metadata$number, 4)
  expect_that(res@gene_clusters_metadata$number, is_a("numeric"))


  # =======================================================
  # Test parameters in res@cluster_list
  expect_equal(length(res@gene_clusters_metadata$cluster_id), 4)
  expect_equal(res@gene_clusters_metadata$cluster_id, c(1, 2, 3, 4))
  expect_that(res@gene_clusters_metadata$cluster_id, is_a("numeric"))
})


# ==============================================================================
# Test no_dknn_filter argument
# ==============================================================================


test_that("Checking that no_dknn_filter is working...", {
  m <- create_4_rnd_clust()

  res <- find_gene_clusters(
    data = m,
    distance_method = "pearson",
    no_dknn_filter = TRUE,
    name = "test",
    output_path = ".",
    inflation = 2,
    k = 75,
    row_sum = -Inf,
    highest = 0.3,
    min_nb_supporting_cell = 0,
    fdr = 1e-8
  )

  expect_equal(ncol(m), ncol(res))
  expect_equal(ncol(m), ncol(res))
  expect_equal(
    paste(colnames(m), collapse = ""),
    paste(colnames(res), collapse = "")
  )
  expect_equal(unlist(res@gene_clusters[[1]]), c(
    "gene302", "gene301", "gene303", "gene305", "gene306", "gene308",
    "gene309", "gene310", "gene304", "gene311", "gene312", "gene313",
    "gene314", "gene315", "gene316", "gene317", "gene318", "gene319",
    "gene320", "gene321", "gene322", "gene323", "gene324", "gene325",
    "gene326", "gene327", "gene328", "gene329", "gene330", "gene331",
    "gene332", "gene333", "gene334", "gene335", "gene336", "gene337",
    "gene338", "gene339", "gene340", "gene341", "gene342", "gene343",
    "gene344", "gene345", "gene346", "gene349", "gene350", "gene351",
    "gene352", "gene353", "gene354", "gene355", "gene356", "gene357",
    "gene358", "gene359", "gene360", "gene361", "gene362", "gene363",
    "gene364", "gene365", "gene366", "gene367", "gene368", "gene369",
    "gene370", "gene371", "gene372", "gene373", "gene374", "gene375",
    "gene376", "gene377", "gene378", "gene379", "gene380", "gene381",
    "gene382", "gene383", "gene384", "gene385", "gene386", "gene387",
    "gene389", "gene390", "gene391", "gene392", "gene393", "gene394",
    "gene395", "gene396", "gene397", "gene398", "gene399", "gene400",
    "gene615", "gene760", "gene859", "gene879", "gene920", "gene1224",
    "gene1393", "gene1423", "gene1454", "gene1644", "gene1901", "gene2054",
    "gene2181", "gene2184", "gene2459", "gene2490", "gene2570", "gene2911",
    "gene2999", "gene3042", "gene3046", "gene3232", "gene3299", "gene3333",
    "gene3609", "gene3841", "gene3849", "gene3933"
  ))
  expect_equal(unlist(res@gene_clusters[[2]]), c(
    "gene2", "gene1", "gene4", "gene5", "gene6", "gene3",
    "gene7", "gene9", "gene10", "gene11", "gene12", "gene8",
    "gene13", "gene14", "gene16", "gene17", "gene19", "gene20",
    "gene21", "gene22", "gene23", "gene24", "gene25", "gene26",
    "gene27", "gene28", "gene29", "gene30", "gene31", "gene32",
    "gene33", "gene34", "gene35", "gene36", "gene37", "gene38",
    "gene39", "gene40", "gene41", "gene42", "gene43", "gene44",
    "gene45", "gene46", "gene47", "gene48", "gene50", "gene51",
    "gene52", "gene54", "gene55", "gene56", "gene57", "gene58",
    "gene59", "gene61", "gene63", "gene64", "gene66", "gene67",
    "gene68", "gene69", "gene70", "gene71", "gene73", "gene74",
    "gene75", "gene76", "gene77", "gene78", "gene79", "gene80",
    "gene81", "gene82", "gene83", "gene84", "gene85", "gene86",
    "gene87", "gene88", "gene89", "gene90", "gene91", "gene93",
    "gene94", "gene95", "gene96", "gene97", "gene98", "gene99",
    "gene100", "gene577", "gene658", "gene713", "gene743", "gene804",
    "gene806", "gene877", "gene898", "gene916", "gene1012", "gene1277",
    "gene1426", "gene1486", "gene1528", "gene1828", "gene2104", "gene2260",
    "gene2562", "gene2565", "gene2586", "gene2658", "gene2710", "gene2962",
    "gene3067", "gene3241", "gene3251", "gene3316", "gene3542", "gene3745",
    "gene3813", "gene3827", "gene3977"
  ))
  expect_equal(unlist(res@gene_clusters[[3]]), c(
    "gene202", "gene201", "gene203", "gene205", "gene206", "gene207",
    "gene208", "gene209", "gene210", "gene204", "gene211", "gene212",
    "gene213", "gene214", "gene215", "gene216", "gene217", "gene218",
    "gene219", "gene220", "gene221", "gene222", "gene223", "gene224",
    "gene225", "gene226", "gene227", "gene228", "gene229", "gene230",
    "gene231", "gene232", "gene233", "gene234", "gene235", "gene236",
    "gene237", "gene238", "gene239", "gene240", "gene241", "gene242",
    "gene243", "gene244", "gene245", "gene246", "gene247", "gene248",
    "gene249", "gene250", "gene251", "gene252", "gene253", "gene254",
    "gene255", "gene256", "gene257", "gene258", "gene259", "gene260",
    "gene261", "gene262", "gene263", "gene264", "gene265", "gene266",
    "gene267", "gene268", "gene269", "gene270", "gene271", "gene272",
    "gene273", "gene274", "gene275", "gene276", "gene277", "gene278",
    "gene279", "gene280", "gene281", "gene282", "gene283", "gene284",
    "gene285", "gene286", "gene287", "gene288", "gene289", "gene290",
    "gene291", "gene292", "gene293", "gene294", "gene295", "gene296",
    "gene297", "gene298", "gene299", "gene300", "gene847", "gene893",
    "gene1375", "gene1931", "gene2036", "gene2157", "gene2431", "gene2859",
    "gene3991"
  ))
  expect_equal(unlist(res@gene_clusters[[4]]), c(
    "gene103", "gene101", "gene104", "gene105", "gene102", "gene106",
    "gene107", "gene108", "gene109", "gene110", "gene111", "gene112",
    "gene113", "gene114", "gene115", "gene116", "gene117", "gene118",
    "gene119", "gene120", "gene121", "gene122", "gene123", "gene124",
    "gene125", "gene126", "gene127", "gene128", "gene129", "gene130",
    "gene131", "gene132", "gene133", "gene134", "gene135", "gene136",
    "gene137", "gene138", "gene139", "gene140", "gene141", "gene142",
    "gene143", "gene144", "gene145", "gene146", "gene147", "gene148",
    "gene149", "gene150", "gene151", "gene152", "gene153", "gene154",
    "gene155", "gene156", "gene157", "gene158", "gene159", "gene160",
    "gene161", "gene162", "gene163", "gene164", "gene165", "gene166",
    "gene167", "gene168", "gene169", "gene170", "gene171", "gene172",
    "gene173", "gene174", "gene175", "gene176", "gene177", "gene178",
    "gene179", "gene180", "gene181", "gene182", "gene183", "gene184",
    "gene185", "gene186", "gene187", "gene188", "gene189", "gene190",
    "gene191", "gene192", "gene193", "gene194", "gene195", "gene196",
    "gene197", "gene198", "gene199", "gene200"
  ))
  expect_equal(length(res@gene_clusters), 4)
  expect_equal(round(sum(res@data), 3), 2236.921)
})


# ==============================================================================
# Test distance argument
# ==============================================================================


test_that("Checking that kendall-based distance is working...", {


  # Create an output directory in the current folder
  dir.create(path = "tmp_output", showWarnings = F)

  # Create a input matrix for find_gene_clusters
  m <- create_4_rnd_clust()

  res <- find_gene_clusters(
    data = m,
    distance_method = "kendall",
    name = "test",
    dist_threads = 4,
    output_path = "tmp_output",
    inflation = 2,
    k = 75,
    row_sum = -Inf,
    highest = 0.3,
    min_nb_supporting_cell = 0,
    fdr = 1e-8
  )

  expect_equal(ncol(m), ncol(res))
  expect_equal(ncol(m), ncol(res))
  expect_equal(colnames(res@data), paste0("sample", seq(1, 20)))

  expect_equal(unlist(res@gene_clusters[[1]]), c(
    "gene150", "gene126", "gene155", "gene198", "gene103", "gene107",
    "gene108", "gene111", "gene112", "gene116", "gene119", "gene120",
    "gene121", "gene122", "gene124", "gene133", "gene136", "gene137",
    "gene139", "gene141", "gene143", "gene154", "gene158", "gene159",
    "gene160", "gene161", "gene163", "gene165", "gene168", "gene171",
    "gene173", "gene176", "gene183", "gene191", "gene192", "gene193",
    "gene197", "gene199", "gene101", "gene104", "gene106", "gene109",
    "gene113", "gene114", "gene115", "gene118", "gene127", "gene131",
    "gene132", "gene140", "gene142", "gene146", "gene147", "gene148",
    "gene149", "gene152", "gene153", "gene162", "gene167", "gene175",
    "gene177", "gene178", "gene179", "gene184", "gene186", "gene188",
    "gene189", "gene190", "gene194", "gene102", "gene105", "gene110",
    "gene123", "gene128", "gene129", "gene134", "gene135", "gene138",
    "gene144", "gene151", "gene164", "gene166", "gene169", "gene172",
    "gene180", "gene181", "gene182", "gene185", "gene195", "gene200",
    "gene117", "gene125", "gene130", "gene145", "gene157", "gene170",
    "gene174", "gene187", "gene196", "gene156", "gene838", "gene1616",
    "gene1856", "gene3528", "gene2573", "gene2725", "gene3485", "gene3488",
    "gene1503", "gene1651", "gene1915", "gene2112", "gene2223", "gene2421",
    "gene2553", "gene2662", "gene2902"
  ))

  expect_equal(unlist(res@gene_clusters[[2]]), c(
    "gene270", "gene202", "gene219", "gene235", "gene229", "gene242",
    "gene245", "gene262", "gene269", "gene273", "gene278", "gene285",
    "gene286", "gene288", "gene289", "gene300", "gene3991", "gene203",
    "gene206", "gene207", "gene211", "gene212", "gene214", "gene215",
    "gene217", "gene220", "gene223", "gene225", "gene226", "gene227",
    "gene230", "gene236", "gene240", "gene241", "gene248", "gene250",
    "gene251", "gene253", "gene255", "gene256", "gene258", "gene261",
    "gene272", "gene275", "gene276", "gene277", "gene279", "gene281",
    "gene282", "gene283", "gene284", "gene287", "gene290", "gene293",
    "gene294", "gene296", "gene299", "gene201", "gene208", "gene213",
    "gene222", "gene224", "gene228", "gene232", "gene233", "gene234",
    "gene237", "gene238", "gene239", "gene244", "gene246", "gene247",
    "gene249", "gene252", "gene254", "gene257", "gene259", "gene263",
    "gene266", "gene267", "gene268", "gene280", "gene291", "gene292",
    "gene297", "gene298", "gene1931", "gene2930", "gene3610", "gene3924"
  ))

  expect_equal(unlist(res@gene_clusters[[3]]), c(
    "gene318", "gene315", "gene320", "gene334", "gene364", "gene366",
    "gene369", "gene382", "gene387", "gene390", "gene303", "gene306",
    "gene312", "gene313", "gene314", "gene316", "gene322", "gene324",
    "gene331", "gene339", "gene350", "gene362", "gene363", "gene365",
    "gene378", "gene379", "gene386", "gene393", "gene398", "gene301",
    "gene311", "gene326", "gene327", "gene329", "gene330", "gene335",
    "gene336", "gene340", "gene341", "gene349", "gene351", "gene353",
    "gene358", "gene368", "gene372", "gene373", "gene389", "gene394",
    "gene317", "gene319", "gene323", "gene332", "gene337", "gene345",
    "gene352", "gene355", "gene360", "gene367", "gene370", "gene385",
    "gene397", "gene2184", "gene2911", "gene302", "gene304", "gene310",
    "gene325", "gene328", "gene342", "gene344", "gene359", "gene371",
    "gene375", "gene376", "gene391", "gene392", "gene396", "gene400",
    "gene760", "gene1423", "gene1922", "gene2490", "gene3609"
  ))

  expect_equal(unlist(res@gene_clusters[[4]]), c(
    "gene37", "gene19", "gene61", "gene64", "gene84", "gene2",
    "gene7", "gene12", "gene27", "gene28", "gene45", "gene57",
    "gene76", "gene80", "gene88", "gene1", "gene4", "gene9",
    "gene13", "gene16", "gene29", "gene31", "gene32", "gene36",
    "gene51", "gene55", "gene56", "gene59", "gene67", "gene70",
    "gene73", "gene78", "gene79", "gene94", "gene10", "gene11",
    "gene34", "gene39", "gene74", "gene82", "gene83", "gene85",
    "gene86", "gene87", "gene93", "gene95", "gene96", "gene3",
    "gene6", "gene14", "gene17", "gene20", "gene25", "gene35",
    "gene42", "gene43", "gene46", "gene52", "gene54", "gene58",
    "gene63", "gene66", "gene71", "gene90", "gene98", "gene99",
    "gene21"
  ))

  expect_equal(length(res@gene_clusters), 4)
  expect_equal(round(sum(res@data), 3), 2414.211)

  # Test output directory and file
  out <- file.exists("tmp_output/test.dbf_out.txt")
  expect_equal(out, TRUE)
  # Remove temporary files
  file.remove("tmp_output/test.dbf_out.txt")
  file.remove("tmp_output/test.mcl_out.txt")
  unlink("tmp_output", recursive = T)
})



test_that("Checking that cosine-based distance is working...", {
  m <- create_4_rnd_clust()

  res <- find_gene_clusters(
    data = m,
    distance_method = "cosine",
    name = "test",
    dist_threads = 4,
    output_path = ".",
    inflation = 2,
    k = 75,
    row_sum = -Inf,
    highest = 0.3,
    min_nb_supporting_cell = 0,
    fdr = 1e-8
  )

  expect_equal(ncol(m), ncol(res))
  expect_equal(ncol(m), ncol(res))
  expect_equal(colnames(res@data), paste0("sample", seq(1, 20)))

  expect_equal(unlist(res@gene_clusters[[1]]), c(
    "gene393", "gene316", "gene398", "gene330", "gene368", "gene382",
    "gene386", "gene379", "gene364", "gene390", "gene389", "gene315",
    "gene312", "gene349", "gene334", "gene318", "gene329", "gene339",
    "gene358", "gene314", "gene353", "gene324", "gene332", "gene397",
    "gene362", "gene365", "gene367", "gene327", "gene400", "gene320",
    "gene366", "gene322", "gene301", "gene303", "gene394", "gene383",
    "gene359", "gene391", "gene345", "gene331", "gene351", "gene363",
    "gene370", "gene311", "gene385", "gene355", "gene396", "gene399",
    "gene372", "gene323", "gene326", "gene350", "gene340", "gene319",
    "gene313", "gene344", "gene336", "gene306", "gene342", "gene395",
    "gene341", "gene380", "gene392", "gene346", "gene352", "gene373",
    "gene335", "gene333", "gene375", "gene369", "gene377", "gene308",
    "gene356", "gene325", "gene317", "gene304", "gene302", "gene371",
    "gene381", "gene387", "gene357", "gene305", "gene388", "gene361",
    "gene384", "gene310", "gene378", "gene338", "gene347", "gene337",
    "gene307", "gene354", "gene376", "gene348", "gene309", "gene328",
    "gene321", "gene360", "gene343", "gene2430", "gene1616", "gene604",
    "gene374", "gene1224", "gene1197", "gene3746", "gene2911", "gene2666",
    "gene2153", "gene3285", "gene1524", "gene542", "gene515", "gene2229",
    "gene2704"
  ))

  expect_equal(unlist(res@gene_clusters[[2]]), c(
    "gene67", "gene76", "gene88", "gene16", "gene55", "gene59",
    "gene32", "gene73", "gene80", "gene12", "gene9", "gene39",
    "gene66", "gene35", "gene45", "gene29", "gene2", "gene36",
    "gene56", "gene6", "gene19", "gene74", "gene86", "gene84",
    "gene71", "gene78", "gene94", "gene82", "gene37", "gene11",
    "gene57", "gene1", "gene89", "gene25", "gene58", "gene99",
    "gene79", "gene54", "gene93", "gene96", "gene44", "gene46",
    "gene70", "gene7", "gene85", "gene87", "gene42", "gene31",
    "gene28", "gene13", "gene10", "gene34", "gene27", "gene14",
    "gene64", "gene75", "gene48", "gene33", "gene23", "gene20",
    "gene95", "gene21", "gene15", "gene100", "gene5", "gene97",
    "gene38", "gene81", "gene17", "gene83", "gene22", "gene65",
    "gene52", "gene61", "gene40", "gene51", "gene4", "gene69",
    "gene3", "gene68", "gene26", "gene47", "gene98", "gene24",
    "gene49", "gene50", "gene91", "gene77", "gene41", "gene90",
    "gene18", "gene63", "gene60", "gene8", "gene658", "gene3183",
    "gene1266", "gene53", "gene30", "gene43", "gene877", "gene92",
    "gene3316", "gene650", "gene72", "gene1426", "gene1077", "gene1444"
  ))

  expect_equal(unlist(res@gene_clusters[[3]]), c(
    "gene285", "gene230", "gene256", "gene298", "gene286", "gene249",
    "gene245", "gene289", "gene282", "gene223", "gene293", "gene212",
    "gene222", "gene267", "gene241", "gene259", "gene214", "gene275",
    "gene283", "gene272", "gene206", "gene250", "gene299", "gene233",
    "gene263", "gene251", "gene253", "gene225", "gene216", "gene236",
    "gene239", "gene290", "gene248", "gene203", "gene219", "gene217",
    "gene273", "gene235", "gene300", "gene279", "gene287", "gene262",
    "gene266", "gene244", "gene215", "gene229", "gene207", "gene258",
    "gene268", "gene240", "gene297", "gene261", "gene255", "gene291",
    "gene278", "gene242", "gene284", "gene277", "gene232", "gene247",
    "gene227", "gene234", "gene270", "gene269", "gene254", "gene226",
    "gene294", "gene218", "gene288", "gene237", "gene238", "gene280",
    "gene213", "gene292", "gene220", "gene296", "gene208", "gene246",
    "gene281", "gene252", "gene295", "gene211", "gene210", "gene257",
    "gene260", "gene205", "gene201", "gene224", "gene271", "gene265",
    "gene264", "gene228", "gene221", "gene274", "gene231", "gene243",
    "gene276", "gene209", "gene202", "gene2761", "gene204", "gene1322",
    "gene1931", "gene3843"
  ))

  expect_equal(unlist(res@gene_clusters[[4]]), c(
    "gene150", "gene189", "gene190", "gene165", "gene146", "gene155",
    "gene186", "gene192", "gene132", "gene166", "gene180", "gene153",
    "gene159", "gene111", "gene144", "gene160", "gene147", "gene112",
    "gene143", "gene122", "gene176", "gene117", "gene184", "gene161",
    "gene114", "gene197", "gene108", "gene135", "gene107", "gene137",
    "gene106", "gene129", "gene133", "gene193", "gene191", "gene157",
    "gene124", "gene162", "gene177", "gene171", "gene158", "gene173",
    "gene119", "gene140", "gene105", "gene178", "gene183", "gene104",
    "gene101", "gene198", "gene121", "gene148", "gene194", "gene141",
    "gene188", "gene127", "gene200", "gene142", "gene145", "gene126",
    "gene138", "gene182", "gene168", "gene103", "gene154", "gene151",
    "gene175", "gene136", "gene179", "gene115", "gene134", "gene109",
    "gene174", "gene167", "gene199", "gene130", "gene181", "gene185",
    "gene128", "gene164", "gene163", "gene120", "gene152", "gene170",
    "gene118", "gene131", "gene116", "gene123", "gene125", "gene149",
    "gene113", "gene156", "gene195", "gene102", "gene139", "gene187",
    "gene172", "gene169", "gene110", "gene196"
  ))

  expect_equal(length(res@gene_clusters), 4)
  expect_equal(round(sum(res@data), 3), 2208.373)
})


test_that("Checking that euclidean-based distance is working...", {
  m <- create_4_rnd_clust()

  res <- find_gene_clusters(
    data = m,
    distance_method = "euclidean",
    name = "test",
    dist_threads = 4,
    output_path = ".",
    inflation = 1.4,
    k = 5,
    row_sum = -Inf,
    highest = 0.3,
    min_nb_supporting_cell = 0,
    fdr = 1e-8
  )

  expect_equal(ncol(m), ncol(res))
  expect_equal(ncol(m), ncol(res))
  expect_equal(colnames(res@data), paste0("sample", seq(1, 20)))

  expect_equal(unlist(res@gene_clusters[[1]]), c(
    "gene1015", "gene3169", "gene1076", "gene1521", "gene2800", "gene3224",
    "gene2589", "gene2433", "gene2044", "gene3478", "gene2042", "gene1430",
    "gene3365", "gene1178", "gene2437", "gene1778", "gene744", "gene1400",
    "gene2799", "gene3841", "gene1334"
  ))

  expect_equal(unlist(res@gene_clusters[[2]]), c(
    "gene3462", "gene568", "gene1873", "gene796", "gene3209", "gene2866",
    "gene660", "gene3660", "gene1581", "gene3784", "gene1519"
  ))

  expect_equal(unlist(res@gene_clusters[[3]]), c(
    "gene1147", "gene3122", "gene541", "gene1459", "gene3195", "gene1446",
    "gene864", "gene1523", "gene3196", "gene1332", "gene3739"
  ))

  expect_equal(length(res@gene_clusters), 3)
  expect_equal(round(sum(res@data), 3), -46.176)
})


# ==============================================================================
# Test highest argument
# ==============================================================================


test_that("Checking stop if highest argument > 1 or <0", {
  # Create matrix containing 4 signatures
  m <- create_4_rnd_clust()

  expect_error(find_gene_clusters(
    data = m,
    name = "test",
    distance_method = "pearson",
    inflation = 2,
    k = 75,
    row_sum = -Inf,
    highest = 1.1,
    min_nb_supporting_cell = 0,
    fdr = 1e-8,
    output_path = tempdir()
  ))

  expect_error(find_gene_clusters(
    data = m,
    name = "test",
    distance_method = "pearson",
    inflation = 2,
    k = 75,
    row_sum = -Inf,
    highest = -0.1,
    min_nb_supporting_cell = 0,
    fdr = 1e-8,
    output_path = tempdir()
  ))
})


# ==============================================================================
# Test min_pct_gene_expressed argument
# ==============================================================================


test_that("Checking stop if min_pct_gene_expressed argument > 100 or < 0", {
  # Create matrix containing 4 signatures
  m <- create_4_rnd_clust()

  expect_error(find_gene_clusters(
    data = m,
    name = "test",
    distance_method = "pearson",
    inflation = 2,
    k = 75,
    row_sum = -Inf,
    highest = 0.3,
    min_nb_supporting_cell = 2,
    min_pct_gene_expressed = 101,
    fdr = 1e-8,
    output_path = tempdir()
  ))

  expect_error(find_gene_clusters(
    data = m,
    name = "test",
    distance_method = "pearson",
    inflation = 2,
    k = 75,
    row_sum = -Inf,
    highest = -0.3,
    min_nb_supporting_cell = 2,
    min_pct_gene_expressed = -0.1,
    fdr = 1e-8,
    output_path = tempdir()
  ))
})


# ==============================================================================
# Test output_path argument
# ==============================================================================


test_that("Checking stop if output directory provided does not exist", {
  # Create matrix containing 4 signatures
  m <- create_4_rnd_clust()

  expect_error(find_gene_clusters(
    data = m,
    name = "test",
    distance_method = "pearson",
    inflation = 2,
    k = 75,
    row_sum = -Inf,
    highest = 0.3,
    min_nb_supporting_cell = 2,
    fdr = 1e-8,
    output_path = "not_a_directory"
  ))
})


# ==============================================================================
# Test filtering based on min_nb_supporting_cell and min_pct_gene_expressed args
# ==============================================================================

test_that("Checking find_gene_clusters() varying min_nb_supporting_cell\
          and min_pct_gene_expressed arguments", {
  # Create matrix containing 4 signatures
  m <- create_4_rnd_clust()

  # Args set to min_nb_supporting_cell = 4 & min_pct_gene_expressed = 90
  res <- find_gene_clusters(
    data = m,
    name = "test",
    distance_method = "pearson",
    inflation = 2,
    k = 75,
    row_sum = -Inf,
    highest = 0.3,
    min_nb_supporting_cell = 4,
    min_pct_gene_expressed = 90,
    min_cluster_size = 0,
    fdr = 1e-8,
    output_path = tempdir()
  )

  expect_equal(res@gene_clusters_metadata$number, 7)


  # Args set to min_nb_supporting_cell = 4 & min_pct_gene_expressed = 50
  res <- find_gene_clusters(
    data = m,
    name = "test",
    distance_method = "pearson",
    inflation = 2,
    k = 75,
    row_sum = -Inf,
    highest = 0.3,
    min_nb_supporting_cell = 4,
    min_pct_gene_expressed = 50,
    min_cluster_size = 0,
    fdr = 1e-8,
    output_path = tempdir()
  )

  expect_equal(res@gene_clusters_metadata$number, 9)
})


# ==============================================================================
# Test filtering based cluster size
# ==============================================================================

test_that("Checking find_gene_clusters() when min_cluster_size\
          argument is set to 5", {
  # Create matrix containing 4 signatures
  m <- create_4_rnd_clust()

  # Args set to min_nb_supporting_cell = 4 & min_pct_gene_expressed = 90
  res <- find_gene_clusters(
    data = m,
    name = "test",
    distance_method = "pearson",
    inflation = 2,
    k = 75,
    row_sum = -Inf,
    highest = 0.3,
    min_nb_supporting_cell = 0,
    min_cluster_size = 5,
    fdr = 1e-8,
    output_path = tempdir()
  )

  expect_equal(res@gene_clusters_metadata$number, 6)
})


test_that("Checking find_gene_clusters() when min_cluster_size\
          argument is set to 50", {
  # Create matrix containing 4 signatures
  m <- create_4_rnd_clust()

  # Args set to min_nb_supporting_cell = 4 & min_pct_gene_expressed = 90
  res <- find_gene_clusters(
    data = m,
    name = "test",
    distance_method = "pearson",
    inflation = 2,
    k = 75,
    row_sum = -Inf,
    highest = 0.3,
    min_nb_supporting_cell = 0,
    min_cluster_size = 50,
    fdr = 1e-8,
    output_path = tempdir()
  )

  expect_equal(res@gene_clusters_metadata$number, 4)
})


test_that("Checking find_gene_clusters() with euclidean distance.", {
  
  set_verbosity(0)
  data("complex9Noisy")
  res <- find_gene_clusters(data=complex9Noisy[ ,1:2],
                            distance_method="euclidean",
                            inflation = 1.25,
                            k=20,
                            min_nb_supporting_cell=0,
                            highest = 0.95,
                            row_sum = -Inf,
                            fdr = 0.0001)
  
  expect_equal(res@gene_clusters_metadata$number, 8)
  expect_equal(paste0(res@gene_clusters_metadata$size, collapse = " "), 
               "1023 782 419 373 352 126 122 89")
  expect_equal(ncol(res@data), 2)
  expect_equal(nrow(res@data), 3286)
})
