set_verbosity(0)
test_that("Just some check for create_3_rnd_clust()", {
  m <- create_3_rnd_clust()
  expect_equal(ncol(m), 20)
  expect_equal(nrow(m), 4000)
  expect_equal(round(sum(m), 2), 4904.76)
  expect_equal(round(sd(m), 2), 1.17)
  expect_equal(round(mean(m), 2), 0.06)
  expect_equal(round(median(m), 2), 0.02)
  expect_true(is.matrix(m))
})
