

test_that("Checking DBF is writting the output in the correct directory...", {
  set_verbosity(0)
  
  #Create matrix containing 4 signatures
  m <- create_4_rnd_clust()
  
  #Create an output directory in the current folder
  dir.create(path = "tmp_output", showWarnings = F)
  #Run DBF
  res <- find_gene_clusters(data = m,
                            output_path = "tmp_output",
                            name = "test_",
                            distance_method = "pearson",
                            k = 50,
                            fdr = 10,
                            inflation = 2,
                            seed = 123)
  #Test results
  out <- file.exists("tmp_output/test_.dbf_out.txt")
  expect_equal(out, TRUE)
  #Remove temporary files
  file.remove("tmp_output/test_.dbf_out.txt")
  file.remove("tmp_output/test_.mcl_out.txt")
  unlink("tmp_output", recursive = T)
})


test_that("Checking output matrix generated by find_gene_clusters...", {
  #Create matrix containing 4 signatures
  m <- create_4_rnd_clust()
  
  ## A rather stringent version
  res <- find_gene_clusters(
    data = m,
    name = "test",
    distance_method = "pearson",
    inflation = 2,
    k = 75,
    row_sum = -Inf,
    highest = 0.3,
    min_nb_supporting_cell = 0,
    fdr = 1e-8, 
    output_path = tempdir()
  )
  
  #=======================================================
  # Test name of temporary files
  expect_equal(res@parameters$filename, "test")
  expect_false(file.exists("test.dbf_out.txt"))
  expect_false(file.exists("test.mcl_out.txt"))
  expect_equal(length(res@parameters$filename), 1)
  expect_that(res@parameters$filename, is_a("character"))
  
  
  #=======================================================
  # Test matrix in res@data
  expect_equal(round(sum(res@data), 3), 2146.661)
  expect_equal(round(mean(res@data), 6), 0.312924)
  expect_equal(round(median(res@data), 6), 0.090583)
  expect_equal(round(sd(res@data), 6), 2.181212)
  
  expect_equal(round(sum(quantile(res@data)["0%"]), 6), -5.806817)
  expect_equal(round(sum(quantile(res@data)["25%"]), 6), -1.056961)
  expect_equal(round(sum(quantile(res@data)["50%"]), 6), 0.090583)
  expect_equal(round(sum(quantile(res@data)["75%"]), 6), 1.437996)
  expect_equal(round(sum(quantile(res@data)["100%"]), 6), 7.073935)
  
  expect_equal(round(sum(colMeans(res@data)),5), 6.25849)
  expect_equal(round(sum(rowMeans(res@data)),4), 107.3331)
  
  expect_equal(round(max(res@data),6), 7.073935)
  
  expect_equal(ncol(res@data), 20)
  expect_equal(colnames(res@data), paste0("sample", seq(1,20)))
  
  expect_equal(nrow(res@data), 343)
  
  expect_equal(nrow(res@data), length(get_genes(res)))
  expect_equal(rownames(res@data), get_genes(res))
  expect_equal(rownames(res@data), unlist(res@gene_clusters, use.names = F))
  expect_equal(nrow(res@data), length(get_genes(res)))
  expect_equal(nrow(res@data), length(unlist(res@gene_clusters)))
  
  expect_equal(round(sum(res@data^2), 2), 33304.7)
  
  expect_that(res@data, is_a("matrix"))
  
  expect_equal(length(res@data), 6860)
  
  
  #=======================================================
  # Test observed distances in res@dbf_output$dknn
  expect_equal(round(sum(res@dbf_output$dknn), 3), 2070.863)
  expect_equal(round(mean(res@dbf_output$dknn), 7), 0.5177157)
  expect_equal(round(median(res@dbf_output$dknn), 7), 0.5333734)
  expect_equal(round(sd(res@dbf_output$dknn), 6), 0.058557)
  
  expect_equal(round(sum(quantile(res@dbf_output$dknn)["0%"]), 6), 0.151747)
  expect_equal(round(sum(quantile(res@dbf_output$dknn)["25%"]), 6), 0.52163)
  expect_equal(round(sum(quantile(res@dbf_output$dknn)["50%"]), 6), 0.533373)
  expect_equal(round(sum(quantile(res@dbf_output$dknn)["75%"]), 6), 0.541248)
  expect_equal(round(sum(quantile(res@dbf_output$dknn)["100%"]), 6), 0.569402)
  
  expect_equal(length(res@dbf_output$dknn), 4000)
  
  expect_equal(round(sum(res@dbf_output$dknn^2), 2), 1085.83)
  
  expect_that(res@dbf_output$dknn, is_a("numeric"))
  
  
  #=======================================================
  # Test simulated distances in res@dbf_output$simulated_dknn
  expect_equal(round(sum(res@dbf_output$simulated_dknn), 3), 2153.312)
  expect_equal(round(mean(res@dbf_output$simulated_dknn), 7), 0.538328)
  expect_equal(round(median(res@dbf_output$simulated_dknn), 7), 0.538304)
  expect_equal(round(sd(res@dbf_output$simulated_dknn), 6), 0.009098)
  
  expect_equal(round(sum(quantile(res@dbf_output$simulated_dknn)["0%"]), 6), 0.504041)
  expect_equal(round(sum(quantile(res@dbf_output$simulated_dknn)["25%"]), 6), 0.532663)
  expect_equal(round(sum(quantile(res@dbf_output$simulated_dknn)["50%"]), 6), 0.538304)
  expect_equal(round(sum(quantile(res@dbf_output$simulated_dknn)["75%"]), 6), 0.544447)
  expect_equal(round(sum(quantile(res@dbf_output$simulated_dknn)["100%"]), 6), 0.572353)
  
  expect_equal(length(res@dbf_output$simulated_dknn), 4000)
  
  expect_equal(round(sum(res@dbf_output$simulated_dknn^2), 2), 1159.52)
  
  expect_that(res@dbf_output$simulated_dknn, is_a("numeric"))
  
  
  #=======================================================
  # Test critical distance in res@critical_distance
  expect_equal(round(res@dbf_output$critical_distance, 7), 0.4772475)
  expect_that(res@dbf_output$critical_distance, is_a("numeric"))
  expect_equal(length(res@dbf_output$critical_distance), 1)
  
  
  #=======================================================
  # Test gene clusters in res@gene_clusters
  expect_equal(sum(as.numeric(names(res@gene_clusters))), 10)
  expect_equal(names(res@gene_clusters), c("1","2","3","4"))
  expect_equal(length(unlist(res@gene_clusters)), 343)
  expect_equal(length(unlist(res@gene_clusters$`1`)), 104)
  expect_equal(length(unlist(res@gene_clusters$`2`)), 99)
  expect_equal(length(unlist(res@gene_clusters$`3`)), 76)
  expect_equal(length(unlist(res@gene_clusters$`4`)), 64)
  
  expect_equal(unlist(res@gene_clusters, use.names = F), get_genes(res))
  expect_equal(unlist(res@gene_clusters$`1`, use.names = F), get_genes(res, cluster = 1))
  expect_equal(unlist(res@gene_clusters$`2`, use.names = F), get_genes(res, cluster = 2))
  expect_equal(unlist(res@gene_clusters$`3`, use.names = F), get_genes(res, cluster = 3))
  expect_equal(unlist(res@gene_clusters$`4`, use.names = F), get_genes(res, cluster = 4))
  expect_equal(unlist(res@gene_clusters, use.names = F), rownames(res@data))
  
  expect_that(res@gene_clusters, is_a("list"))
  expect_that(res@gene_clusters$`1`, is_a("character"))
  
  
  #=======================================================
  # Test size of gene clusters in res@gene_clusters_metadata$size
  expect_equal(res@gene_clusters_metadata$size, c("1" = 104,
                                                  "2" = 99,
                                                  "3" = 76,
                                                  "4" = 64))
  expect_that(res@gene_clusters_metadata$size, is_a("integer"))
  expect_equal(max(res@gene_clusters_metadata$size), 104)
  expect_equal(min(res@gene_clusters_metadata$size), 64)
  expect_equal(length(res@gene_clusters_metadata$size), 4)
  
  expect_equal(res@gene_clusters_metadata$size[1],
               c("1" = length(res@gene_clusters$`1`)))
  expect_equal(res@gene_clusters_metadata$size[2],
               c("2" = length(res@gene_clusters$`2`)))
  expect_equal(res@gene_clusters_metadata$size[3],
               c("3" = length(res@gene_clusters$`3`)))
  expect_equal(res@gene_clusters_metadata$size[4],
               c("4" = length(res@gene_clusters$`4`)))
  expect_equal(res@gene_clusters_metadata$size[1],
               c("1" = length(get_genes(res, cluster = 1))))
  expect_equal(res@gene_clusters_metadata$size[2],
               c("2" = length(get_genes(res, cluster = 2))))
  expect_equal(res@gene_clusters_metadata$size[3],
               c("3" = length(get_genes(res, cluster = 3))))
  expect_equal(res@gene_clusters_metadata$size[4],
               c("4" = length(get_genes(res, cluster = 4))))
  
  
  #=======================================================
  # Test parameters in res@parameters
  expect_that(res@parameters, is_a("list"))
  expect_equal(length(res@parameters), 11)
  expect_equal(names(res@parameters), c("filename", 
                                        "distance_method", 
                                        "k", 
                                        "inflation", 
                                        "highest",
                                        "fdr",
                                        "min_nb_supporting_cell",
                                        "min_pct_gene_expressed",
                                        "min_cluster_size",
                                        "row_sum",
                                        "seed"))
  
  expect_equal(res@parameters$distance_method, "pearson")
  expect_that(res@parameters$distance_method, is_a("character"))
  expect_equal(length(res@parameters$distance_method), 1)
  
  expect_equal(res@parameters$k, 75)
  expect_that(res@parameters$k, is_a("numeric"))
  expect_equal(length(res@parameters$k), 1)
  
  expect_equal(res@parameters$inflation, 2)
  expect_that(res@parameters$inflation, is_a("numeric"))
  expect_equal(length(res@parameters$inflation), 1)
  
  expect_equal(res@parameters$highest, 0.3)
  expect_that(res@parameters$highest, is_a("numeric"))
  expect_equal(length(res@parameters$highest), 1)
  
  expect_equal(res@parameters$fdr, 1e-08)
  expect_that(res@parameters$fdr, is_a("numeric"))
  expect_equal(length(res@parameters$fdr), 1)
  
  expect_equal(res@parameters$min_nb_supporting_cell, 0)
  expect_that(res@parameters$min_nb_supporting_cell, is_a("numeric"))
  expect_equal(length(res@parameters$min_nb_supporting_cell), 1)
  
  expect_equal(res@parameters$min_pct_gene_expressed, 40)
  expect_that(res@parameters$min_pct_gene_expressed, is_a("numeric"))
  expect_equal(length(res@parameters$min_pct_gene_expressed), 1)
  
  expect_equal(res@parameters$min_cluster_size, 10)
  expect_that(res@parameters$min_cluster_size, is_a("numeric"))
  expect_equal(length(res@parameters$min_cluster_size), 1)
  
  expect_equal(res@parameters$row_sum, -Inf)
  expect_that(res@parameters$row_sum, is_a("numeric"))
  expect_equal(length(res@parameters$row_sum), 1)
  
  expect_equal(res@parameters$seed, 123)
  expect_that(res@parameters$seed, is_a("numeric"))
  expect_equal(length(res@parameters$seed), 1)
  
  
  #=======================================================
  # Test parameters in res@cluster_number
  expect_equal(res@gene_clusters_metadata$number, 4)
  expect_that(res@gene_clusters_metadata$number, is_a("numeric"))
  
  
  #=======================================================
  # Test parameters in res@cluster_list
  expect_equal(length(res@gene_clusters_metadata$cluster_id), 4)
  expect_equal(res@gene_clusters_metadata$cluster_id, c(1,2,3,4))
  expect_that(res@gene_clusters_metadata$cluster_id, is_a("numeric"))
  
})







test_that("Checking that no_dknn_filter is working...", {
  
  set_verbosity(0)
  
  m <- create_4_rnd_clust()
  
  res <- find_gene_clusters(data=m,
                            distance_method="pearson",
                            no_dknn_filter = TRUE,
                            name = "test",
                            output_path = ".",
                            inflation = 2,
                            k=75,
                            row_sum=-Inf,
                            highest=0.3,
                            min_nb_supporting_cell = 0,
                            fdr = 1e-8)
  
  expect_equal(ncol(m), ncol(res))
  expect_equal(ncol(m), ncol(res))
  expect_equal(paste(colnames(m), collapse = ""), paste(colnames(res), collapse = ""))
  expect_equal(paste0(unlist(res@gene_clusters[[1]]), collapse = ""),
               "gene302gene301gene303gene305gene306gene308gene309gene310gene304gene311gene312gene313gene314gene315gene316gene317gene318gene319gene320gene321gene322gene323gene324gene325gene326gene327gene328gene329gene330gene331gene332gene333gene334gene335gene336gene337gene338gene339gene340gene341gene342gene343gene344gene345gene346gene349gene350gene351gene352gene353gene354gene355gene356gene357gene358gene359gene360gene361gene362gene363gene364gene365gene366gene367gene368gene369gene370gene371gene372gene373gene374gene375gene376gene377gene378gene379gene380gene381gene382gene383gene384gene385gene386gene387gene389gene390gene391gene392gene393gene394gene395gene396gene397gene398gene399gene400gene615gene760gene859gene879gene920gene1224gene1393gene1423gene1454gene1644gene1901gene2054gene2181gene2184gene2459gene2490gene2570gene2911gene2999gene3042gene3046gene3232gene3299gene3333gene3609gene3841gene3849gene3933")
  expect_equal(paste0(unlist(res@gene_clusters[[2]]), collapse = ""), "gene2gene1gene4gene5gene6gene3gene7gene9gene10gene11gene12gene8gene13gene14gene16gene17gene19gene20gene21gene22gene23gene24gene25gene26gene27gene28gene29gene30gene31gene32gene33gene34gene35gene36gene37gene38gene39gene40gene41gene42gene43gene44gene45gene46gene47gene48gene50gene51gene52gene54gene55gene56gene57gene58gene59gene61gene63gene64gene66gene67gene68gene69gene70gene71gene73gene74gene75gene76gene77gene78gene79gene80gene81gene82gene83gene84gene85gene86gene87gene88gene89gene90gene91gene93gene94gene95gene96gene97gene98gene99gene100gene577gene658gene713gene743gene804gene806gene877gene898gene916gene1012gene1277gene1426gene1486gene1528gene1828gene2104gene2260gene2562gene2565gene2586gene2658gene2710gene2962gene3067gene3241gene3251gene3316gene3542gene3745gene3813gene3827gene3977")
  expect_equal(paste0(unlist(res@gene_clusters[[3]]), collapse = ""), "gene202gene201gene203gene205gene206gene207gene208gene209gene210gene204gene211gene212gene213gene214gene215gene216gene217gene218gene219gene220gene221gene222gene223gene224gene225gene226gene227gene228gene229gene230gene231gene232gene233gene234gene235gene236gene237gene238gene239gene240gene241gene242gene243gene244gene245gene246gene247gene248gene249gene250gene251gene252gene253gene254gene255gene256gene257gene258gene259gene260gene261gene262gene263gene264gene265gene266gene267gene268gene269gene270gene271gene272gene273gene274gene275gene276gene277gene278gene279gene280gene281gene282gene283gene284gene285gene286gene287gene288gene289gene290gene291gene292gene293gene294gene295gene296gene297gene298gene299gene300gene847gene893gene1375gene1931gene2036gene2157gene2431gene2859gene3991")
  expect_equal(paste0(unlist(res@gene_clusters[[4]]), collapse = ""), "gene103gene101gene104gene105gene102gene106gene107gene108gene109gene110gene111gene112gene113gene114gene115gene116gene117gene118gene119gene120gene121gene122gene123gene124gene125gene126gene127gene128gene129gene130gene131gene132gene133gene134gene135gene136gene137gene138gene139gene140gene141gene142gene143gene144gene145gene146gene147gene148gene149gene150gene151gene152gene153gene154gene155gene156gene157gene158gene159gene160gene161gene162gene163gene164gene165gene166gene167gene168gene169gene170gene171gene172gene173gene174gene175gene176gene177gene178gene179gene180gene181gene182gene183gene184gene185gene186gene187gene188gene189gene190gene191gene192gene193gene194gene195gene196gene197gene198gene199gene200")
  expect_equal(length(res@gene_clusters), 4)
  expect_equal(round(sum(res@data), 3), 2236.921)
})



test_that("Checking that kendall-based distance is working...", {
  
  set_verbosity(3)
  
  m <- create_4_rnd_clust()
  
  res <- find_gene_clusters(data=m,
                            distance_method="kendall",
                            name = "test",
                            dist_threads = 4,
                            output_path = ".",
                            inflation = 2,
                            k=75,
                            row_sum=-Inf,
                            highest=0.3,
                            min_nb_supporting_cell = 0,
                            fdr = 1e-8)
  
  expect_equal(ncol(m), ncol(res))
  expect_equal(ncol(m), ncol(res))
  expect_equal(colnames(res@data), paste0("sample", seq(1,20)))
  
  expect_equal(unlist(res@gene_clusters[[1]]), c(
    "gene150", "gene126", "gene155", "gene198", "gene103", "gene107",
    "gene108", "gene111", "gene112", "gene116", "gene119", "gene120",
    "gene121", "gene122", "gene124", "gene133", "gene136", "gene137",
    "gene139", "gene141", "gene143", "gene154", "gene158", "gene159",
    "gene160", "gene161", "gene163", "gene165", "gene168", "gene171",
    "gene173", "gene176", "gene183", "gene191", "gene192", "gene193",
    "gene197", "gene199", "gene101", "gene104", "gene106", "gene109",
    "gene113", "gene114", "gene115", "gene118", "gene127", "gene131",
    "gene132", "gene140", "gene142", "gene146", "gene147", "gene148",
    "gene149", "gene152", "gene153", "gene162", "gene167", "gene175",
    "gene177", "gene178", "gene179", "gene184", "gene186", "gene188",
    "gene189", "gene190", "gene194", "gene102", "gene105", "gene110",
    "gene123", "gene128", "gene129", "gene134", "gene135", "gene138",
    "gene144", "gene151", "gene164", "gene166", "gene169", "gene172",
    "gene180", "gene181", "gene182", "gene185", "gene195", "gene200",
    "gene117", "gene125", "gene130", "gene145", "gene157", "gene170",
    "gene174", "gene187", "gene196", "gene156", "gene838", "gene1616",
    "gene1856", "gene3528", "gene2573", "gene2725", "gene3485", "gene3488",
    "gene1503", "gene1651", "gene1915", "gene2112", "gene2223", "gene2421",
    "gene2553", "gene2662", "gene2902"
  ))
  
  expect_equal(unlist(res@gene_clusters[[2]]), c(
    "gene270", "gene202", "gene219", "gene235", "gene229", "gene242",
    "gene245", "gene262", "gene269", "gene273", "gene278", "gene285",
    "gene286", "gene288", "gene289", "gene300", "gene3991", "gene203",
    "gene206", "gene207", "gene211", "gene212", "gene214", "gene215",
    "gene217", "gene220", "gene223", "gene225", "gene226", "gene227",
    "gene230", "gene236", "gene240", "gene241", "gene248", "gene250",
    "gene251", "gene253", "gene255", "gene256", "gene258", "gene261",
    "gene272", "gene275", "gene276", "gene277", "gene279", "gene281",
    "gene282", "gene283", "gene284", "gene287", "gene290", "gene293",
    "gene294", "gene296", "gene299", "gene201", "gene208", "gene213",
    "gene222", "gene224", "gene228", "gene232", "gene233", "gene234",
    "gene237", "gene238", "gene239", "gene244", "gene246", "gene247",
    "gene249", "gene252", "gene254", "gene257", "gene259", "gene263",
    "gene266", "gene267", "gene268", "gene280", "gene291", "gene292",
    "gene297", "gene298", "gene1931", "gene2930", "gene3610", "gene3924"
  ))
  
  expect_equal(unlist(res@gene_clusters[[3]]), c(
    "gene318", "gene315", "gene320", "gene334", "gene364", "gene366",
    "gene369", "gene382", "gene387", "gene390", "gene303", "gene306",
    "gene312", "gene313", "gene314", "gene316", "gene322", "gene324",
    "gene331", "gene339", "gene350", "gene362", "gene363", "gene365",
    "gene378", "gene379", "gene386", "gene393", "gene398", "gene301",
    "gene311", "gene326", "gene327", "gene329", "gene330", "gene335",
    "gene336", "gene340", "gene341", "gene349", "gene351", "gene353",
    "gene358", "gene368", "gene372", "gene373", "gene389", "gene394",
    "gene317", "gene319", "gene323", "gene332", "gene337", "gene345",
    "gene352", "gene355", "gene360", "gene367", "gene370", "gene385",
    "gene397", "gene2184", "gene2911", "gene302", "gene304", "gene310",
    "gene325", "gene328", "gene342", "gene344", "gene359", "gene371",
    "gene375", "gene376", "gene391", "gene392", "gene396", "gene400",
    "gene760", "gene1423", "gene1922", "gene2490", "gene3609"
  ))
  
  expect_equal(unlist(res@gene_clusters[[4]]), c(
    "gene37", "gene19", "gene61", "gene64", "gene84", "gene2",
    "gene7", "gene12", "gene27", "gene28", "gene45", "gene57",
    "gene76", "gene80", "gene88", "gene1", "gene4", "gene9",
    "gene13", "gene16", "gene29", "gene31", "gene32", "gene36",
    "gene51", "gene55", "gene56", "gene59", "gene67", "gene70",
    "gene73", "gene78", "gene79", "gene94", "gene10", "gene11",
    "gene34", "gene39", "gene74", "gene82", "gene83", "gene85",
    "gene86", "gene87", "gene93", "gene95", "gene96", "gene3",
    "gene6", "gene14", "gene17", "gene20", "gene25", "gene35",
    "gene42", "gene43", "gene46", "gene52", "gene54", "gene58",
    "gene63", "gene66", "gene71", "gene90", "gene98", "gene99",
    "gene21"
  ))
  
  expect_equal(length(res@gene_clusters), 4)
  expect_equal(round(sum(res@data), 3), 2414.211)
})


# ==============================================================================
# ==============================================================================


test_that("Checking stop if highest argument > 1 or <0", {
  #Create matrix containing 4 signatures
  m <- create_4_rnd_clust()
  
  expect_error(find_gene_clusters(
    data = m,
    name = "test",
    distance_method = "pearson",
    inflation = 2,
    k = 75,
    row_sum = -Inf,
    highest = 1.1,
    min_nb_supporting_cell = 0,
    fdr = 1e-8, 
    output_path = tempdir()
  ))
  
  expect_error(find_gene_clusters(
    data = m,
    name = "test",
    distance_method = "pearson",
    inflation = 2,
    k = 75,
    row_sum = -Inf,
    highest = -0.1,
    min_nb_supporting_cell = 0,
    fdr = 1e-8, 
    output_path = tempdir()
  ))
})


# ==============================================================================
# ==============================================================================


test_that("Checking stop if min_pct_gene_expressed argument > 100 or <0", {
  #Create matrix containing 4 signatures
  m <- create_4_rnd_clust()
  
  expect_error(find_gene_clusters(
    data = m,
    name = "test",
    distance_method = "pearson",
    inflation = 2,
    k = 75,
    row_sum = -Inf,
    highest = 0.3,
    min_nb_supporting_cell = 2,
    min_pct_gene_expressed = 101,
    fdr = 1e-8, 
    output_path = tempdir()
  ))
  
  expect_error(find_gene_clusters(
    data = m,
    name = "test",
    distance_method = "pearson",
    inflation = 2,
    k = 75,
    row_sum = -Inf,
    highest = -0.3,
    min_nb_supporting_cell = 2,
    min_pct_gene_expressed = -0.1,
    fdr = 1e-8, 
    output_path = tempdir()
  ))
})


# ==============================================================================
# ==============================================================================


test_that("Checking stop if output directory provided does not exist", {
  #Create matrix containing 4 signatures
  m <- create_4_rnd_clust()
  
  expect_error(find_gene_clusters(
    data = m,
    name = "test",
    distance_method = "pearson",
    inflation = 2,
    k = 75,
    row_sum = -Inf,
    highest = 0.3,
    min_nb_supporting_cell = 2,
    fdr = 1e-8, 
    output_path = "not_a_directory"
  ))
  
})
