test_that("Cheking DBFMCL is providing the right number of genes", {
  #Create matrix containing 3 signatures
  set.seed(123)
  m <- matrix(rnorm(80000), nc=20)
  m[1:100, 1:10] <- m[1:100, 1:10] + 3
  m[101:200, 11:20] <- m[101:200, 11:20] + 3
  m[301:400, 5:15] <- m[201:300, 5:15] - 3
  m[201:300, c(1,5,10,15,20)] <- m[201:300, c(1,5,10,15,20)] - 3
  res <- find_gene_clusters(data=m,
                                distance_method="pearson",
                                inflation = 2,
                                k=75,
                                row_sum=-Inf,
                                highest=0.3,
                                min_nb_supporting_cell = 0,
                                fdr = 1e-8)
  
  #Test number of cluster
  expect_equal(length(res@size), 4)
  
  #Test number of genes
  expect_equal(sum(res@size), 436)
  
  #Test number of genes in each gene cluster
  expect_equal(res@size[1], 114)
  expect_equal(res@size[2], 112)
  expect_equal(res@size[3], 106)
  
  #Remove output files
  file.remove("test.dbf_out.txt")
  file.remove("test.mcl_out.txt")
})

<<<<<<< HEAD
# test_that("Checking DBF is writting the output in the correct directory...", {
#   set.seed(123)
#   #Create matrix
#   m <- matrix(rnorm(80000), nc=20)
#   m[1:100, 1:10] <- m[1:100, 1:10] + 3
#   m[101:200, 11:20] <- m[101:200, 11:20] + 3
#   m[301:400, 5:15] <- m[201:300, 5:15] - 3
#   m[201:300, c(1,5,10,15,20)] <- m[201:300, c(1,5,10,15,20)] - 3
#   res <- find_gene_clusters(data=m,
#                             distance_method="pearson",
#                             inflation = 2,
#                             k=75,
#                             row_sum=-Inf,
#                             highest=0.3,
#                             min_nb_supporting_cell = 0,
#                             fdr = 1e-8)
#   #Test results
#   out <- file.exists("tmp_output/test_.dbf_out.txt")
#   expect_equal(out, TRUE)
#   #Remove temporary files
#   file.remove("tmp_output/test_.dbf_out.txt")
#   file.remove("tmp_output/test_.mcl_out.txt")
#   file.remove("tmp_output")
# })
=======




test_that("Checking DBF is writting the output in the correct directory...", {
  set.seed(123)
  #Create matrix
  m <- matrix(rnorm(80000), nc=20)
  m[1:100,1:10] <- m[1:100,1:10] + 4
  m[101:200,11:20] <- m[101:200,11:20] + 3
  m[201:300,5:15] <- m[201:300,5:15] + -2
  #Create an output directory in the current folder
  dir.create(path = "tmp_output")
  #Run DBF
  res <- find_gene_clusters(data = m,
                            output_path = "tmp_output",
                            name = "test_",
                            distance_method = "pearson",
                            k = 50,
                            fdr = 10,
                            silent = FALSE,
                            av_dot_prod_min = 0,
                            inflation = 2,
                            seed = 123)
  #Test results
  out <- file.exists("tmp_output/test_.dbf_out.txt")
  expect_equal(out, TRUE)
  #Remove temporary files
  file.remove("tmp_output/test_.dbf_out.txt")
  file.remove("tmp_output/test_.mcl_out.txt")
  file.remove("tmp_output")
})




test_that("Checking output matrix generated by find_gene_clusters..." {
  #Create matrix containing 3 signatures
  set.seed(123)
  m <- matrix(rnorm(80000), nc=20)
  m[1:100,1:10] <- m[1:100,1:10] + 4
  m[101:200,11:20] <- m[101:200,11:20] + 3
  m[201:300,5:15] <- m[201:300,5:15] + -2
  res <- find_gene_clusters(data=m,
                            name = "test",
                            distance_method="pearson",
                            av_dot_prod_min = 0,
                            inflation = 2,
                            k=50,
                            fdr = 10,
                            seed = 123)
  
  # Test results
  expect_equal(round(sum(res@data), 3), 5086.909)
  expect_equal(round(mean(res@data), 7), 0.6837243)
  expect_equal(round(median(res@data), 7), 0.3038707)
  expect_equal(round(sd(res@data), 6), 2.107101)
  
  expect_equal(round(sum(quantile(res@data)["0%"]), 6), -5.274385)
  expect_equal(round(sum(quantile(res@data)["25%"]), 6), -0.754237)
  expect_equal(round(sum(quantile(res@data)["50%"]), 6), 0.303871)
  expect_equal(round(sum(quantile(res@data)["75%"]), 6), 2.134471)
  expect_equal(round(sum(quantile(res@data)["100%"]), 6), 6.971585)
  
  expect_equal(round(sum(colMeans(res@data)),5), 13.67449)
  expect_equal(round(sum(rowMeans(res@data)),4), 254.3454)
  
  expect_equal(round(max(res@data),6), 6.971585)
  
  expect_equal(ncol(res@data), 20)
  expect_equal(colnames(res@data), paste0("sample", seq(1,20)))
  
  expect_equal(nrow(res@data), 372)
  
  expect_equal(nrow(res@data), length(get_genes(res)))
  expect_equal(rownames(res@data), get_genes(res))
  expect_equal(rownames(res@data), names(res@gene_clusters))
  expect_equal(nrow(res@data), length(get_genes(res)))
  expect_equal(nrow(res@data), length(res@gene_clusters))
  
  expect_equal(round(sum(res@data^2), 2), 36506.27)
  
  expect_that(res@data, is_a("matrix"))
  
  expect_equal(length(res@data), 7440)
  
  #Remove output files
  file.remove("test.dbf_out.txt")
  file.remove("test.mcl_out.txt")
})







test_that("Checking observed distances computed by find_gene_clusters..." {
  #Create matrix containing 3 signatures
  set.seed(123)
  m <- matrix(rnorm(80000), nc=20)
  m[1:100,1:10] <- m[1:100,1:10] + 4
  m[101:200,11:20] <- m[101:200,11:20] + 3
  m[201:300,5:15] <- m[201:300,5:15] + -2
  res <- find_gene_clusters(data=m,
                            name = "test",
                            distance_method="pearson",
                            av_dot_prod_min = 0,
                            inflation = 2,
                            k=50,
                            fdr = 10,
                            seed = 123)
  
  # Test results
  expect_equal(round(sum(res@distances), 3), 1942.611)
  expect_equal(round(mean(res@distances), 7), 0.4856527)
  expect_equal(round(median(res@distances), 7), 0.502099)
  expect_equal(round(sd(res@distances), 6), 0.063969)
  
  expect_equal(round(sum(quantile(res@distances)["0%"]), 6), 0.133025)
  expect_equal(round(sum(quantile(res@distances)["25%"]), 6), 0.491859)
  expect_equal(round(sum(quantile(res@distances)["50%"]), 6), 0.502099)
  expect_equal(round(sum(quantile(res@distances)["75%"]), 6), 0.510083)
  expect_equal(round(sum(quantile(res@distances)["100%"]), 6), 0.536909)
  
  expect_equal(length(res@distances), 4000)
  
  

  
  
  #Remove output files
  file.remove("test.dbf_out.txt")
  file.remove("test.mcl_out.txt")
})

