test_that("Checking DBF is writting the output in the correct directory...", {
  
  #Create matrix
  m <- create_3_rnd_clust()
  
  #Create an output directory in the current folder
  dir.create(path = "tmp_output", showWarnings = F)
  #Run DBF
  res <- DBF(data = m,
             output_path = "tmp_output",
             name = "test_",
             distance_method = "pearson",
             k = 50,
             fdr = 10,
             seed = 123)
  #Test results
  out <- file.exists("tmp_output/test_.dbf_out.txt")
  expect_equal(out, TRUE)
  #Remove temporary files
  file.remove("tmp_output/test_.dbf_out.txt")
  unlink("tmp_output", recursive = T)
})




test_that("Checking output matrix generated by find_gene_clusters...", {
  #Create matrix containing 3 signatures
  m <- create_4_rnd_clust()
  ## Set the level of verbosity
  set_verbosity(2)
  ## A rather stringent version
  res <- DBF(data=m,
             distance_method="pearson",
             k=75,
             row_sum=-Inf,
             highest=0.3,
             fdr = 1e-8,
             name = "test")
  
  #=======================================================
  # Test name of temporary files
  expect_equal(res@parameters$name, "test") # TODO
  expect_true(file.exists("test.dbf_out.txt"))
  expect_equal(length(res@parameters$name), 1)
  expect_that(res@parameters$name, is_a("character"))
  
  
  #=======================================================
  # Test matrix in res@data
  expect_equal(round(sum(res@data), 3), 2188.346) 
  expect_equal(round(mean(res@data), 6), 0.296524)
  expect_equal(round(median(res@data), 6), 0.083721)
  expect_equal(round(sd(res@data), 6), 2.123212)
  
  expect_equal(round(sum(quantile(res@data)["0%"]), 6), -5.806817)
  expect_equal(round(sum(quantile(res@data)["25%"]), 6), -1.013447)
  expect_equal(round(sum(quantile(res@data)["50%"]), 6), 0.083721)
  expect_equal(round(sum(quantile(res@data)["75%"]), 6), 1.34164)
  expect_equal(round(sum(quantile(res@data)["100%"]), 6), 7.073935)
  
  expect_equal(round(sum(colMeans(res@data)),5), 5.93048)
  expect_equal(round(sum(rowMeans(res@data)),4), 109.4173)
  
  expect_equal(round(max(res@data),6), 7.073935)
  
  expect_equal(ncol(res@data), 20)
  expect_equal(colnames(res@data), paste0("sample", seq(1,20)))
  
  expect_equal(nrow(res@data), 369)
  
  expect_equal(nrow(res@data), length(get_genes(res)))
  expect_equal(rownames(res@data), get_genes(res))
  expect_equal(rownames(res@data), unlist(res@gene_clusters, use.names = F))
  expect_equal(nrow(res@data), length(get_genes(res)))
  expect_equal(nrow(res@data), length(unlist(res@gene_clusters, use.names = F)))
  
  expect_equal(round(sum(res@data^2), 2), 33913.65)
  
  expect_that(res@data, is_a("matrix"))
  
  expect_equal(length(res@data), 7380)
  
  
  #=======================================================
  # Test observed distances in res@dbf_output$dknn
  expect_equal(round(sum(res@dbf_output$dknn), 3), 2070.863)
  expect_equal(round(mean(res@dbf_output$dknn), 7), 0.5177157)
  expect_equal(round(median(res@dbf_output$dknn), 7), 0.5333734)
  expect_equal(round(sd(res@dbf_output$dknn), 6), 0.058557)
  
  expect_equal(round(sum(quantile(res@dbf_output$dknn)["0%"]), 6), 0.151747)
  expect_equal(round(sum(quantile(res@dbf_output$dknn)["25%"]), 6), 0.52163)
  expect_equal(round(sum(quantile(res@dbf_output$dknn)["50%"]), 6), 0.533373)
  expect_equal(round(sum(quantile(res@dbf_output$dknn)["75%"]), 6), 0.541248)
  expect_equal(round(sum(quantile(res@dbf_output$dknn)["100%"]), 6), 0.569402)
  
  expect_equal(length(res@dbf_output$dknn), 4000)
  
  expect_equal(round(sum(res@dbf_output$dknn^2), 2), 1085.83)
  
  expect_that(res@dbf_output$dknn, is_a("numeric"))
  
  
  #=======================================================
  # Test simulated distances in res@dbf_output$simulated_dknn
  expect_equal(round(sum(res@dbf_output$simulated_dknn), 3), 2153.312)
  expect_equal(round(mean(res@dbf_output$simulated_dknn), 7), 0.538328)
  expect_equal(round(median(res@dbf_output$simulated_dknn), 7), 0.538304)
  expect_equal(round(sd(res@dbf_output$simulated_dknn), 6), 0.009098)
  
  expect_equal(round(sum(quantile(res@dbf_output$simulated_dknn)["0%"]), 6), 0.504041)
  expect_equal(round(sum(quantile(res@dbf_output$simulated_dknn)["25%"]), 6), 0.532663)
  expect_equal(round(sum(quantile(res@dbf_output$simulated_dknn)["50%"]), 6), 0.538304)
  expect_equal(round(sum(quantile(res@dbf_output$simulated_dknn)["75%"]), 6), 0.544447)
  expect_equal(round(sum(quantile(res@dbf_output$simulated_dknn)["100%"]), 6), 0.572353)
  
  expect_equal(length(res@dbf_output$simulated_dknn), 4000)
  
  expect_equal(round(sum(res@dbf_output$simulated_dknn^2), 2), 1159.52)
  
  expect_that(res@dbf_output$simulated_dknn, is_a("numeric"))
  
  
  #=======================================================
  # Test critical distance in res@critical_distance
  expect_equal(round(res@dbf_output$critical_distance, 7), 0.4772475)
  expect_that(res@dbf_output$critical_distance, is_a("numeric"))
  expect_equal(length(res@dbf_output$critical_distance), 1)
  
  
  #=======================================================
  # Test gene clusters in res@gene_clusters
  expect_equal(names(res@gene_clusters), "1")
  expect_equal(length(res@gene_clusters$`1`), 369)
  
  expect_equal(res@gene_clusters$`1`, get_genes(res))
  expect_equal(res@gene_clusters$`1`, get_genes(res, cluster = 1))
  expect_equal(res@gene_clusters$`1`, rownames(res@data))
  
  expect_that(res@gene_clusters, is_a("list"))
  expect_that(res@gene_clusters$`1`, is_a("character"))
  
  
  #=======================================================
  # Test size of gene clusters in res@gene_clusters_metadata$size
  expect_equal(res@gene_clusters_metadata$size, 369)
  expect_that(res@gene_clusters_metadata$size, is_a("integer"))
  expect_equal(length(res@gene_clusters_metadata$size), 1)
  
  expect_equal(res@gene_clusters_metadata$size[1],
               length(res@gene_clusters$`1`))
  expect_equal(res@gene_clusters_metadata$size[1],
               length(get_genes(res, cluster = 1)))
  
  
  #=======================================================
  # Test parameters in res@parameters
  expect_that(res@parameters, is_a("list"))
  expect_equal(length(res@parameters), 8)
  expect_equal(names(res@parameters), c("algorithm",
                                        "name",
                                        "distance_method",
                                        "k",
                                        "highest",
                                        "fdr",
                                        "row_sum",
                                        "seed"))
  
  expect_equal(res@parameters$algorithm, "DBFMCL")
  expect_that(res@parameters$algorithm, is_a("character"))
  expect_equal(length(res@parameters$algorithm), 1)
  
  expect_equal(res@parameters$distance_method, "pearson")
  expect_that(res@parameters$distance_method, is_a("character"))
  expect_equal(length(res@parameters$distance_method), 1)
  
  expect_equal(res@parameters$k, 75)
  expect_that(res@parameters$k, is_a("numeric"))
  expect_equal(length(res@parameters$k), 1)
  
  expect_equal(res@parameters$highest, 0.3)
  expect_that(res@parameters$highest, is_a("numeric"))
  expect_equal(length(res@parameters$highest), 1)
  
  expect_equal(res@parameters$fdr, 1e-08)
  expect_that(res@parameters$fdr, is_a("numeric"))
  expect_equal(length(res@parameters$fdr), 1)
  
  expect_equal(res@parameters$row_sum, -Inf)
  expect_that(res@parameters$row_sum, is_a("numeric"))
  expect_equal(length(res@parameters$row_sum), 1)
  
  expect_equal(res@parameters$seed, 123)
  expect_that(res@parameters$seed, is_a("numeric"))
  expect_equal(length(res@parameters$seed), 1)
  
  
  #Remove output files
  file.remove("test.dbf_out.txt")
})



