

test_that("Checking DBF is writting the output in the correct directory...", {
  
  set.seed(123)
  set_verbosity(0)
  
  #Create matrix
  
  m <- matrix(rnorm(80000), nc=20)
  m[1:100,1:10] <- m[1:100,1:10] + 4
  m[101:200,11:20] <- m[101:200,11:20] + 3
  m[201:300,5:15] <- m[201:300,5:15] + -2
  #Create an output directory in the current folder
  dir.create(path = "tmp_output", showWarnings = F)
  #Run DBF
  res <- find_gene_clusters(data = m,
                            output_path = "tmp_output",
                            name = "test_",
                            distance_method = "pearson",
                            k = 50,
                            fdr = 10,
                            inflation = 2,
                            seed = 123)
  #Test results
  out <- file.exists("tmp_output/test_.dbf_out.txt")
  expect_equal(out, TRUE)
  #Remove temporary files
  file.remove("tmp_output/test_.dbf_out.txt")
  file.remove("tmp_output/test_.mcl_out.txt")
  removeDirectory("tmp_output")
})


test_that("Checking output matrix generated by find_gene_clusters...", {
  #Create matrix containing 4 signatures
  m <- create_4_rnd_clust()

  ## A rather stringent version
  res <- find_gene_clusters(data=m,
                            distance_method="pearson",
                            name = "test",
                            output_path = ".",
                            inflation = 2,
                            k=75,
                            row_sum=-Inf,
                            highest=0.3,
                            min_nb_supporting_cell = 0,
                            fdr = 1e-8)
  
  #=======================================================
  # Test name of temporary files
  expect_equal(res@name, "test")
  expect_true(file.exists("test.dbf_out.txt"))
  expect_true(file.exists("test.mcl_out.txt"))
  expect_equal(length(res@name), 1)
  expect_that(res@name, is_a("character"))
  
  
  #=======================================================
  # Test matrix in res@data
  expect_equal(round(sum(res@data), 3), 1120.741) 
  expect_equal(round(mean(res@data), 6), 0.132475)
  expect_equal(round(median(res@data), 6), 0.095893)
  expect_equal(round(sd(res@data), 6), 2.191157)
  
  expect_equal(round(sum(quantile(res@data)["0%"]), 6), -6.590108)
  expect_equal(round(sum(quantile(res@data)["25%"]), 6), -1.172559)
  expect_equal(round(sum(quantile(res@data)["50%"]), 6), 0.095893)
  expect_equal(round(sum(quantile(res@data)["75%"]), 6), 1.537619)
  expect_equal(round(sum(quantile(res@data)["100%"]), 6), 6.073935)
  
  expect_equal(round(sum(colMeans(res@data)),5), 2.64951)
  expect_equal(round(sum(rowMeans(res@data)),4), 56.037)
  
  expect_equal(round(max(res@data),6), 6.073935)
  
  expect_equal(ncol(res@data), 20)
  expect_equal(colnames(res@data), paste0("sample", seq(1,20)))
  
  expect_equal(nrow(res@data), 423)
  
  expect_equal(nrow(res@data), length(get_genes(res)))
  expect_equal(rownames(res@data), get_genes(res))
  expect_equal(rownames(res@data), names(res@gene_clusters))
  expect_equal(nrow(res@data), length(get_genes(res)))
  expect_equal(nrow(res@data), length(res@gene_clusters))
  
  expect_equal(round(sum(res@data^2), 2), 40761.56)
  
  expect_that(res@data, is_a("matrix"))
  
  expect_equal(length(res@data), 8460)
  
  
  #=======================================================
  # Test observed distances in res@distances
  expect_equal(round(sum(res@distances), 3), 2056.903)
  expect_equal(round(mean(res@distances), 7), 0.5142258)
  expect_equal(round(median(res@distances), 7), 0.5337578)
  expect_equal(round(sd(res@distances), 6), 0.059838)
  
  expect_equal(round(sum(quantile(res@distances)["0%"]), 6), 0.234982)
  expect_equal(round(sum(quantile(res@distances)["25%"]), 6), 0.52096)
  expect_equal(round(sum(quantile(res@distances)["50%"]), 6), 0.533758)
  expect_equal(round(sum(quantile(res@distances)["75%"]), 6), 0.54178)
  expect_equal(round(sum(quantile(res@distances)["100%"]), 6), 0.570325)
  
  expect_equal(length(res@distances), 4000)
  
  expect_equal(round(sum(res@distances^2), 2), 1072.03)
  
  expect_that(res@distances, is_a("numeric"))
  
  
  #=======================================================
  # Test simulated distances in res@simulated_distances
  expect_equal(round(sum(res@simulated_distances), 3), 2156.411)
  expect_equal(round(mean(res@simulated_distances), 7), 0.5391027)
  expect_equal(round(median(res@simulated_distances), 7), 0.5390122)
  expect_equal(round(sd(res@simulated_distances), 6), 0.008992)
  
  expect_equal(round(sum(quantile(res@simulated_distances)["0%"]), 6), 0.504175)
  expect_equal(round(sum(quantile(res@simulated_distances)["25%"]), 6), 0.53302)
  expect_equal(round(sum(quantile(res@simulated_distances)["50%"]), 6), 0.539012)
  expect_equal(round(sum(quantile(res@simulated_distances)["75%"]), 6), 0.545236)
  expect_equal(round(sum(quantile(res@simulated_distances)["100%"]), 6), 0.57499)
  
  expect_equal(length(res@simulated_distances), 4000)
  
  expect_equal(round(sum(res@simulated_distances^2), 2), 1162.85)
  
  expect_that(res@simulated_distances, is_a("numeric"))
  
  
  #=======================================================
  # Test critical distance in res@critical_distance
  expect_equal(round(res@critical_distance, 7), 0.4800525)
  expect_that(res@critical_distance, is_a("numeric"))
  expect_equal(length(res@critical_distance), 1)
  
  
  #=======================================================
  # Test gene clusters in res@gene_clusters
  expect_equal(round(sum(res@gene_clusters), 3), 1054)
  expect_equal(round(mean(res@gene_clusters), 6), 2.491726)
  expect_equal(median(res@gene_clusters), 2)
  expect_equal(round(sd(res@gene_clusters), 6), 1.120385)
  expect_equal(min(res@gene_clusters), 1)
  expect_equal(max(res@gene_clusters), 4)
  
  expect_equal(unique(res@gene_clusters), c(1,2,3,4))
  expect_equal(length(res@gene_clusters), 423)
  expect_equal(length(res@gene_clusters[res@gene_clusters == 1]), 107)
  expect_equal(length(res@gene_clusters[res@gene_clusters == 2]), 106)
  expect_equal(length(res@gene_clusters[res@gene_clusters == 3]), 105)
  expect_equal(length(res@gene_clusters[res@gene_clusters == 4]), 105)
  
  expect_equal(names(res@gene_clusters), get_genes(res))
  expect_equal(names(res@gene_clusters[res@gene_clusters == 1]), get_genes(res, cluster = 1))
  expect_equal(names(res@gene_clusters[res@gene_clusters == 2]), get_genes(res, cluster = 2))
  expect_equal(names(res@gene_clusters[res@gene_clusters == 3]), get_genes(res, cluster = 3))
  expect_equal(names(res@gene_clusters[res@gene_clusters == 4]), get_genes(res, cluster = 4))
  expect_equal(names(res@gene_clusters), rownames(res@data))
  
  expect_that(res@gene_clusters, is_a("numeric"))
  
  
  #=======================================================
  # Test size of gene clusters in res@size
  expect_equal(res@size, c(107, 106, 105, 105))
  expect_that(res@size, is_a("integer"))
  expect_equal(max(res@size), 107)
  expect_equal(min(res@size), 105)
  expect_equal(length(res@size), 4)
  
  expect_equal(res@size[1], length(res@gene_clusters[res@gene_clusters == 1]))
  expect_equal(res@size[2], length(res@gene_clusters[res@gene_clusters == 2]))
  expect_equal(res@size[3], length(res@gene_clusters[res@gene_clusters == 3]))
  expect_equal(res@size[4], length(res@gene_clusters[res@gene_clusters == 4]))
  expect_equal(res@size[1], length(get_genes(res, cluster = 1)))
  expect_equal(res@size[2], length(get_genes(res, cluster = 2)))
  expect_equal(res@size[3], length(get_genes(res, cluster = 3)))
  expect_equal(res@size[4], length(get_genes(res, cluster = 4)))
  
  
  #=======================================================
  # Test parameters in res@parameters
  expect_that(res@parameters, is_a("list"))
  expect_equal(length(res@parameters), 6)
  expect_equal(names(res@parameters), c("distance_method",
                                        "k",
                                        "fdr",
                                        "seed",
                                        "inflation",
                                        "min_cluster_size"))
  
  expect_equal(res@parameters$distance_method, "pearson")
  expect_that(res@parameters$distance_method, is_a("character"))
  expect_equal(length(res@parameters$distance_method), 1)
  
  expect_equal(res@parameters$k, 75)
  expect_that(res@parameters$k, is_a("numeric"))
  expect_equal(length(res@parameters$k), 1)
  
  expect_equal(res@parameters$fdr, 1e-08)
  expect_that(res@parameters$fdr, is_a("numeric"))
  expect_equal(length(res@parameters$fdr), 1)
  
  expect_equal(res@parameters$seed, 123)
  expect_that(res@parameters$seed, is_a("numeric"))
  expect_equal(length(res@parameters$seed), 1)
  
  expect_equal(res@parameters$inflation, 2)
  expect_that(res@parameters$inflation, is_a("numeric"))
  expect_equal(length(res@parameters$inflation), 1)
  
  expect_equal(res@parameters$min_cluster_size, 10)
  expect_that(res@parameters$min_cluster_size, is_a("numeric"))
  expect_equal(length(res@parameters$min_cluster_size), 1)
  
  #=======================================================
  # Test parameters in res@cluster_number
  expect_equal(res@cluster_number, 4)
  expect_that(res@cluster_number, is_a("numeric"))
  
  #=======================================================
  # Test parameters in res@cluster_list
  expect_equal(length(res@cluster_list), 4)
  expect_equal(res@cluster_list, c(1,2,3,4))
  expect_that(res@cluster_list, is_a("integer"))
  
  #Remove output files
  file.remove("test.dbf_out.txt")
  file.remove("test.mcl_out.txt")
})

test_that("Checking that no_dknn_filter is working...", {
 
  set_verbosity(0)
  
  m <- create_4_rnd_clust()
  
  res <- find_gene_clusters(data=m,
                            distance_method="pearson",
                            no_dknn_filter = TRUE,
                            name = "test",
                            output_path = ".",
                            inflation = 2,
                            k=75,
                            row_sum=-Inf,
                            highest=0.3,
                            min_nb_supporting_cell = 0,
                            fdr = 1e-8)
  
  testthat::expect_equal(ncol(m), ncol(res))
  testthat::expect_equal(ncol(m), ncol(res))
  testthat::expect_equal(paste(colnames(m), collapse = ""), paste(colnames(res), collapse = ""))
  testthat::expect_equal(paste0(unlist(res@gene_clusters[[1]]), collapse = ""),
                         "gene302gene301gene303gene305gene306gene308gene309gene310gene304gene311gene312gene313gene314gene315gene316gene317gene318gene319gene320gene321gene322gene323gene324gene325gene326gene327gene328gene329gene330gene331gene332gene333gene334gene335gene336gene337gene338gene339gene340gene341gene342gene343gene344gene345gene346gene349gene350gene351gene352gene353gene354gene355gene356gene357gene358gene359gene360gene361gene362gene363gene364gene365gene366gene367gene368gene369gene370gene371gene372gene373gene374gene375gene376gene377gene378gene379gene380gene381gene382gene383gene384gene385gene386gene387gene389gene390gene391gene392gene393gene394gene395gene396gene397gene398gene399gene400gene615gene760gene859gene879gene920gene1224gene1393gene1423gene1454gene1644gene1901gene2054gene2181gene2184gene2459gene2490gene2570gene2911gene2999gene3042gene3046gene3232gene3299gene3333gene3609gene3841gene3849gene3933")
  testthat::expect_equal(paste0(unlist(res@gene_clusters[[2]]), collapse = ""), "gene2gene1gene4gene5gene6gene3gene7gene9gene10gene11gene12gene8gene13gene14gene16gene17gene19gene20gene21gene22gene23gene24gene25gene26gene27gene28gene29gene30gene31gene32gene33gene34gene35gene36gene37gene38gene39gene40gene41gene42gene43gene44gene45gene46gene47gene48gene50gene51gene52gene54gene55gene56gene57gene58gene59gene61gene63gene64gene66gene67gene68gene69gene70gene71gene73gene74gene75gene76gene77gene78gene79gene80gene81gene82gene83gene84gene85gene86gene87gene88gene89gene90gene91gene93gene94gene95gene96gene97gene98gene99gene100gene577gene658gene713gene743gene804gene806gene877gene898gene916gene1012gene1277gene1426gene1486gene1528gene1828gene2104gene2260gene2562gene2565gene2586gene2658gene2710gene2962gene3067gene3241gene3251gene3316gene3542gene3745gene3813gene3827gene3977")
  testthat::expect_equal(paste0(unlist(res@gene_clusters[[3]]), collapse = ""), "gene202gene201gene203gene205gene206gene207gene208gene209gene210gene204gene211gene212gene213gene214gene215gene216gene217gene218gene219gene220gene221gene222gene223gene224gene225gene226gene227gene228gene229gene230gene231gene232gene233gene234gene235gene236gene237gene238gene239gene240gene241gene242gene243gene244gene245gene246gene247gene248gene249gene250gene251gene252gene253gene254gene255gene256gene257gene258gene259gene260gene261gene262gene263gene264gene265gene266gene267gene268gene269gene270gene271gene272gene273gene274gene275gene276gene277gene278gene279gene280gene281gene282gene283gene284gene285gene286gene287gene288gene289gene290gene291gene292gene293gene294gene295gene296gene297gene298gene299gene300gene847gene893gene1375gene1931gene2036gene2157gene2431gene2859gene3991")
  testthat::expect_equal(paste0(unlist(res@gene_clusters[[3]]), collapse = ""), "gene103gene101gene104gene105gene102gene106gene107gene108gene109gene110gene111gene112gene113gene114gene115gene116gene117gene118gene119gene120gene121gene122gene123gene124gene125gene126gene127gene128gene129gene130gene131gene132gene133gene134gene135gene136gene137gene138gene139gene140gene141gene142gene143gene144gene145gene146gene147gene148gene149gene150gene151gene152gene153gene154gene155gene156gene157gene158gene159gene160gene161gene162gene163gene164gene165gene166gene167gene168gene169gene170gene171gene172gene173gene174gene175gene176gene177gene178gene179gene180gene181gene182gene183gene184gene185gene186gene187gene188gene189gene190gene191gene192gene193gene194gene195gene196gene197gene198gene199gene200")
  testthat::expect_equal(length(res@gene_clusters), 4)
  testthat::expect_equal(round(sum(res@data), 3), 2236.921)
})
