test_that("Checking DBF is writting the output in the correct directory...", {

  #Create matrix
  m <- create_3_rnd_clust()
  
  #Create an output directory in the current folder
  dir.create(path = "tmp_output", showWarnings = F)
  #Run DBF
  res <- DBF(data = m,
             output_path = "tmp_output",
             name = "test_",
             distance_method = "pearson",
             k = 50,
             fdr = 10,
             seed = 123)
  #Test results
  out <- file.exists("tmp_output/test_.dbf_out.txt")
  expect_equal(out, TRUE)
  #Remove temporary files
  file.remove("tmp_output/test_.dbf_out.txt")
  removeDirectory("tmp_output")
})




test_that("Checking output matrix generated by find_gene_clusters...", {
  #Create matrix containing 3 signatures
  m <- create_3_rnd_clust()
  ## Set the level of verbosity
  set_verbosity(2)
  ## A rather stringent version
  res <- DBF(data = m, name = "test",
             output_path = ".",
             distance_method = "pearson",
             k = 75,
             row_sum=-Inf,
             highest=0.3,
             fdr = 1e-8)
  
  #=======================================================
  # Test name of temporary files
  # expect_equal(res@name, "test") # TODO
  expect_true(file.exists("test.dbf_out.txt"))
  # expect_equal(length(res@name), 1)
  expect_that(res@name, is_a("character"))
  
  
  #=======================================================
  # Test matrix in res@data
  expect_equal(round(sum(res@data), 3), 1120.741) 
  expect_equal(round(mean(res@data), 6), 0.132475)
  expect_equal(round(median(res@data), 6), 0.095893)
  expect_equal(round(sd(res@data), 6), 2.191157)
  
  expect_equal(round(sum(quantile(res@data)["0%"]), 6), -6.590108)
  expect_equal(round(sum(quantile(res@data)["25%"]), 6), -1.172559)
  expect_equal(round(sum(quantile(res@data)["50%"]), 6), 0.095893)
  expect_equal(round(sum(quantile(res@data)["75%"]), 6), 1.537619)
  expect_equal(round(sum(quantile(res@data)["100%"]), 6), 6.073935)
  
  expect_equal(round(sum(colMeans(res@data)),5), 2.64951)
  expect_equal(round(sum(rowMeans(res@data)),4), 56.037)
  
  expect_equal(round(max(res@data),6), 6.073935)
  
  expect_equal(ncol(res@data), 20)
  expect_equal(colnames(res@data), paste0("sample", seq(1,20)))
  
  expect_equal(nrow(res@data), 423)
  
  expect_equal(nrow(res@data), length(get_genes(res)))
  expect_equal(rownames(res@data), get_genes(res))
  expect_equal(rownames(res@data), names(res@gene_clusters))
  expect_equal(nrow(res@data), length(get_genes(res)))
  expect_equal(nrow(res@data), length(res@gene_clusters))
  
  expect_equal(round(sum(res@data^2), 2), 40761.56)
  
  expect_that(res@data, is_a("matrix"))
  
  expect_equal(length(res@data), 8460)
  
  
  #=======================================================
  # Test observed distances in res@distances
  expect_equal(round(sum(res@distances), 3), 2056.903)
  expect_equal(round(mean(res@distances), 7), 0.5142258)
  expect_equal(round(median(res@distances), 7), 0.5337578)
  expect_equal(round(sd(res@distances), 6), 0.059838)
  
  expect_equal(round(sum(quantile(res@distances)["0%"]), 6), 0.234982)
  expect_equal(round(sum(quantile(res@distances)["25%"]), 6), 0.52096)
  expect_equal(round(sum(quantile(res@distances)["50%"]), 6), 0.533758)
  expect_equal(round(sum(quantile(res@distances)["75%"]), 6), 0.54178)
  expect_equal(round(sum(quantile(res@distances)["100%"]), 6), 0.570325)
  
  expect_equal(length(res@distances), 4000)
  
  expect_equal(round(sum(res@distances^2), 2), 1072.03)
  
  expect_that(res@distances, is_a("numeric"))
  
  
  #=======================================================
  # Test simulated distances in res@simulated_distances
  expect_equal(round(sum(res@simulated_distances), 3), 2156.411)
  expect_equal(round(mean(res@simulated_distances), 7), 0.5391027)
  expect_equal(round(median(res@simulated_distances), 7), 0.5390122)
  expect_equal(round(sd(res@simulated_distances), 6), 0.008992)
  
  expect_equal(round(sum(quantile(res@simulated_distances)["0%"]), 6), 0.504175)
  expect_equal(round(sum(quantile(res@simulated_distances)["25%"]), 6), 0.53302)
  expect_equal(round(sum(quantile(res@simulated_distances)["50%"]), 6), 0.539012)
  expect_equal(round(sum(quantile(res@simulated_distances)["75%"]), 6), 0.545236)
  expect_equal(round(sum(quantile(res@simulated_distances)["100%"]), 6), 0.57499)
  
  expect_equal(length(res@simulated_distances), 4000)
  
  expect_equal(round(sum(res@simulated_distances^2), 2), 1162.85)
  
  expect_that(res@simulated_distances, is_a("numeric"))
  
  
  #=======================================================
  # Test critical distance in res@critical_distance
  expect_equal(round(res@critical_distance, 7), 0.4800525)
  expect_that(res@critical_distance, is_a("numeric"))
  expect_equal(length(res@critical_distance), 1)
  
  
  #=======================================================
  # Test gene clusters in res@gene_clusters
  expect_equal(round(sum(res@gene_clusters), 3), 1054)
  expect_equal(round(mean(res@gene_clusters), 6), 2.491726)
  expect_equal(median(res@gene_clusters), 2)
  expect_equal(round(sd(res@gene_clusters), 6), 1.120385)
  expect_equal(min(res@gene_clusters), 1)
  expect_equal(max(res@gene_clusters), 4)
  
  expect_equal(unique(res@gene_clusters), c(1,2,3,4))
  expect_equal(length(res@gene_clusters), 423)
  expect_equal(length(res@gene_clusters[res@gene_clusters == 1]), 107)
  expect_equal(length(res@gene_clusters[res@gene_clusters == 2]), 106)
  expect_equal(length(res@gene_clusters[res@gene_clusters == 3]), 105)
  expect_equal(length(res@gene_clusters[res@gene_clusters == 4]), 105)
  
  expect_equal(names(res@gene_clusters), get_genes(res))
  expect_equal(names(res@gene_clusters[res@gene_clusters == 1]), get_genes(res, cluster = 1))
  expect_equal(names(res@gene_clusters[res@gene_clusters == 2]), get_genes(res, cluster = 2))
  expect_equal(names(res@gene_clusters[res@gene_clusters == 3]), get_genes(res, cluster = 3))
  expect_equal(names(res@gene_clusters[res@gene_clusters == 4]), get_genes(res, cluster = 4))
  expect_equal(names(res@gene_clusters), rownames(res@data))
  
  expect_that(res@gene_clusters, is_a("numeric"))
  
  
  #=======================================================
  # Test size of gene clusters in res@size
  expect_equal(res@size, c(107, 106, 105, 105))
  expect_that(res@size, is_a("integer"))
  expect_equal(max(res@size), 107)
  expect_equal(min(res@size), 105)
  expect_equal(length(res@size), 4)
  
  expect_equal(res@size[1], length(res@gene_clusters[res@gene_clusters == 1]))
  expect_equal(res@size[2], length(res@gene_clusters[res@gene_clusters == 2]))
  expect_equal(res@size[3], length(res@gene_clusters[res@gene_clusters == 3]))
  expect_equal(res@size[4], length(res@gene_clusters[res@gene_clusters == 4]))
  expect_equal(res@size[1], length(get_genes(res, cluster = 1)))
  expect_equal(res@size[2], length(get_genes(res, cluster = 2)))
  expect_equal(res@size[3], length(get_genes(res, cluster = 3)))
  expect_equal(res@size[4], length(get_genes(res, cluster = 4)))
  
  
  #=======================================================
  # Test parameters in res@parameters
  expect_that(res@parameters, is_a("list"))
  expect_equal(length(res@parameters), 6)
  expect_equal(names(res@parameters), c("distance_method",
                                        "k",
                                        "fdr",
                                        "seed",
                                        "inflation",
                                        "min_cluster_size"))
  
  expect_equal(res@parameters$distance_method, "pearson")
  expect_that(res@parameters$distance_method, is_a("character"))
  expect_equal(length(res@parameters$distance_method), 1)
  
  expect_equal(res@parameters$k, 75)
  expect_that(res@parameters$k, is_a("numeric"))
  expect_equal(length(res@parameters$k), 1)
  
  expect_equal(res@parameters$fdr, 1e-08)
  expect_that(res@parameters$fdr, is_a("numeric"))
  expect_equal(length(res@parameters$fdr), 1)
  
  expect_equal(res@parameters$seed, 123)
  expect_that(res@parameters$seed, is_a("numeric"))
  expect_equal(length(res@parameters$seed), 1)
  
  expect_equal(res@parameters$inflation, 2)
  expect_that(res@parameters$inflation, is_a("numeric"))
  expect_equal(length(res@parameters$inflation), 1)
  
  expect_equal(res@parameters$min_cluster_size, 10)
  expect_that(res@parameters$min_cluster_size, is_a("numeric"))
  expect_equal(length(res@parameters$min_cluster_size), 1)
  
  #Remove output files
  file.remove("test.dbf_out.txt")
})



