#################################################################
##    Define cell_clust function for ClusterSet object
#################################################################

#' @title
#' Cell clustering
#' @description
#' Identify clusters of cells by cutting the dendrogram generated by the hierarchical clustering algorithm. 
#' The dendrogram is cut using the hybrid method of the DynamicTreeCut R package which is based on the shape of the dendrogram branches.
#' For a full description of the algorithm, see Peter Langfelder, Bin Zhang, Steve Horvath, Defining clusters from a hierarchical cluster tree: the Dynamic Tree Cut package for R, Bioinformatics, 2008.
#' @param object A \code{ClusterSet} object.
#' @param min_cluster_size Minimum cluster size.
#'
#' @return 
#' @export cell_clust
#'
#' @examples
#' \dontrun{
#' ## with an artificial dataset
#' m <- matrix(rnorm(80000), nc=20)
#' m[1:100,1:10] <- m[1:100,1:10] + 4
#' m[101:200,11:20] <- m[101:200,11:20] + 3
#' m[201:300,5:15] <- m[201:300,5:15] + -2
#' 
#' res <- DBFMCL(data=m,
#'               distance_method="pearson",
#'               av_dot_prod_min = 0,
#'               inflation = 1.2,
#'               k=25,
#'               fdr = 10)
#'               
#' res <- cell_clust(res, min_cluster_size = 3)
#' res@cell_clust
#' }


cell_clust <- function(object,
                       min_cluster_size = 5) {
  
  # Row centering (Soustract the row mean values for each value in a row)
  data_rc <- sweep(object@data, MARGIN = 1, FUN = "-", STATS = rowMeans(object@data))
  
  # Cell clustering
  m_dist <- as.dist(1 - cor(data_rc, method = "pearson"))
  m_clust <- hclust(m_dist, method = "average")
  
  # Cell partitionning - cut tree
  ct <- cutreeHybrid(m_clust, minClusterSize = min_cluster_size,
                     distM = as.matrix(m_dist),
                     deepSplit = 1,
                     useMedoids=T,
                     pamStage = T)
  
  # Put cell partitioning result in ClusterSet object
  cell_clusters <- ct$labels
  object@cell_clusters <- as.numeric(cell_clusters)
  names(object@cell_clusters) <- colnames(object@data)
  
  return(object)
}
