#################################################################
##    Define find_cell_clusters function for ClusterSet object
#################################################################

#' @title
#' Cell clustering
#' @description
#' Identify clusters of cells by cutting the dendrogram generated by the hierarchical clustering algorithm. 
#' The dendrogram is cut using the hybrid method of the DynamicTreeCut R package which is based on the shape of the dendrogram branches.
#' For a full description of the algorithm, see Peter Langfelder, Bin Zhang, Steve Horvath, Defining clusters from a hierarchical cluster tree: the Dynamic Tree Cut package for R, Bioinformatics, 2008.
#' @param object A \code{ClusterSet} object.
#' @param min_cluster_size Minimum cluster size.
#'
#' @return A \code{ClusterSet} object.
#' @export find_cell_clusters
#'
#' @examples
#' \dontrun{
#' ## with an artificial dataset
#' m <- create_4_rnd_clust()
#' 
#' res <- find_gene_clusters(data=m,
#'                              distance_method="pearson",
#'                              inflation = 2,
#'                              k=75,
#'                              row_sum=-Inf,
#'                              highest=0.3,
#'                              min_nb_supporting_cell = 0,
#'                              fdr = 1e-8)
#'               
#' res <- find_cell_clusters(res, min_cluster_size = 3)
#' res@cell_clust
#' }


find_cell_clusters <- function(object,
                       min_cluster_size = 5) {
  
  # Row centering (Soustract the row mean values for each value in a row)
  data_rc <- sweep(object@data, MARGIN = 1, FUN = "-", STATS = rowMeans(object@data))
  
  # Cell clustering
  m_dist <- as.dist(1 - cor(data_rc, method = "pearson"))
  m_clust <- hclust(m_dist, method = "average")
  
  # Store clustering results in ClusterSet object
  object@cell_clusters$hclust_res <- m_clust
  
  # Cell partitionning - cut tree
  ct <- cutreeHybrid(m_clust, minClusterSize = min_cluster_size,
                     distM = as.matrix(m_dist),
                     deepSplit = 1,
                     useMedoids=T,
                     pamStage = T)
  
  # Put cell partitioning result in ClusterSet object
  cell_clusters <- ct$labels
  object@cell_clusters$labels <- as.numeric(cell_clusters)
  names(object@cell_clusters$labels) <- colnames(object@data)
  
  # Put core cellsof each partition
  cell_cores <- ct$cores
  object@cell_clusters$cores <- as.numeric(cell_cores)
  names(object@cell_clusters$cores) <- colnames(object@data)
  
  return(object)
}
