#################################################################
##    Define the load_seurat function for class ClusterSet
#################################################################

#' @title
#' load_seurat
#' @description
#' Load a seurat object into a ClusterSet object. At the moment the objective is mainly
#' to store cell identity (i.e cell types/groups to barcode mapping) and
#' cell type to color mapping.
#' @param object A ClusterSet object.
#' @param seurat_obj A seurat object to extract cell to group mapping.
#' @param dimplot_obj To display cell clusters on the profile diagram with colors extracted from Dimplot output (provide also a Seurat object).
#
#' @return A ClusterSet object.
#' @export
#'
#' @examples
#' # see online examples
setGeneric("load_seurat",
           function(object,
                    seurat_obj=NULL,
                    dimplot_obj=NULL) {
             standardGeneric("load_seurat")
           })

#' @rdname load_seurat
setMethod("load_seurat",
          signature(object = "ClusterSet"),
          function(object,
                   seurat_obj=NULL,
                   dimplot_obj=NULL) {
            if (!inherits(seurat_obj, "Seurat")) {
              stop("Please provide a Seurat and patchwork object.")
            }
            if (!inherits(dimplot_obj, "patchwork")) {
              stop("Please provide a Seurat and patchwork object.")
            }
            if(ncol(object) != ncol(seurat_obj)){
              stop("The number of cells is not the same in ClusterSet object and Seurat object.")
            }
            
            g <- ggplot_build(dimplot_obj)
            
            # Load colors associated to cells from DimPlot generated by seurat
            object@cells_metadata[,"cell_colors_from_seurat"] <- g$data[[1]][,"colour"]
            
            # Load cell legend from DimPlot generated by seurat
            object@cells_metadata[,"cell_legend_from_seurat"] <- g$data[[1]][,"group"]
            
            # Load cell order from DimPlot generated by seurat
            object@cells_metadata[,"cell_order_from_seurat"] <- order(g$plot$data$ident)
            
            return(object)
          }
)